package entity;
// Generated 03 29, 19 5:28:16 PM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * AppResults generated by hbm2java
 */
@Entity
@Table(name="app_results"
    ,catalog="seniorhighdb"
)
public class AppResults  implements java.io.Serializable {


     private Long resultId;
     private String AFcL;
     private Integer AFcS;
     private String AFdL;
     private Integer AFdS;
     private String AInL;
     private Integer AInS;
     private String AMrL;
     private Integer AMrS;
     private String ANfL;
     private Integer ANfS;
     private String APaL;
     private Integer APaS;
     private String ASaL;
     private Integer ASaS;
     private String ASdL;
     private Integer ASdS;
     private String AVeL;
     private Integer AVeS;
     private String AVfL;
     private Integer AVfS;
     private String arSy;
     private Date arTs;
     private String encouraged;
     private Integer epAg;
     private Integer epEd;
     private Integer epEmc;
     private Integer epHa;
     private Integer epHw;
     private Integer epSbl;
     private Integer epSc;
     private Integer epSe;
     private Integer epTc;
     private String mayEnroll;
     private ShApplicant shApplicant;
     private Date testDate;

    public AppResults() {
    }

	
    public AppResults(Date arTs, ShApplicant shApplicant) {
        this.arTs = arTs;
        this.shApplicant = shApplicant;
    }
    public AppResults(String AFcL, Integer AFcS, String AFdL, Integer AFdS, String AInL, Integer AInS, String AMrL, Integer AMrS, String ANfL, Integer ANfS, String APaL, Integer APaS, String ASaL, Integer ASaS, String ASdL, Integer ASdS, String AVeL, Integer AVeS, String AVfL, Integer AVfS, String arSy, Date arTs, String encouraged, Integer epAg, Integer epEd, Integer epEmc, Integer epHa, Integer epHw, Integer epSbl, Integer epSc, Integer epSe, Integer epTc, String mayEnroll, ShApplicant shApplicant, Date testDate) {
       this.AFcL = AFcL;
       this.AFcS = AFcS;
       this.AFdL = AFdL;
       this.AFdS = AFdS;
       this.AInL = AInL;
       this.AInS = AInS;
       this.AMrL = AMrL;
       this.AMrS = AMrS;
       this.ANfL = ANfL;
       this.ANfS = ANfS;
       this.APaL = APaL;
       this.APaS = APaS;
       this.ASaL = ASaL;
       this.ASaS = ASaS;
       this.ASdL = ASdL;
       this.ASdS = ASdS;
       this.AVeL = AVeL;
       this.AVeS = AVeS;
       this.AVfL = AVfL;
       this.AVfS = AVfS;
       this.arSy = arSy;
       this.arTs = arTs;
       this.encouraged = encouraged;
       this.epAg = epAg;
       this.epEd = epEd;
       this.epEmc = epEmc;
       this.epHa = epHa;
       this.epHw = epHw;
       this.epSbl = epSbl;
       this.epSc = epSc;
       this.epSe = epSe;
       this.epTc = epTc;
       this.mayEnroll = mayEnroll;
       this.shApplicant = shApplicant;
       this.testDate = testDate;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="result_id", unique=true, nullable=false)
    public Long getResultId() {
        return this.resultId;
    }
    
    public void setResultId(Long resultId) {
        this.resultId = resultId;
    }

    
    @Column(name="a_fc_l", length=5)
    public String getAFcL() {
        return this.AFcL;
    }
    
    public void setAFcL(String AFcL) {
        this.AFcL = AFcL;
    }

    
    @Column(name="a_fc_s")
    public Integer getAFcS() {
        return this.AFcS;
    }
    
    public void setAFcS(Integer AFcS) {
        this.AFcS = AFcS;
    }

    
    @Column(name="a_fd_l", length=5)
    public String getAFdL() {
        return this.AFdL;
    }
    
    public void setAFdL(String AFdL) {
        this.AFdL = AFdL;
    }

    
    @Column(name="a_fd_s")
    public Integer getAFdS() {
        return this.AFdS;
    }
    
    public void setAFdS(Integer AFdS) {
        this.AFdS = AFdS;
    }

    
    @Column(name="a_in_l", length=5)
    public String getAInL() {
        return this.AInL;
    }
    
    public void setAInL(String AInL) {
        this.AInL = AInL;
    }

    
    @Column(name="a_in_s")
    public Integer getAInS() {
        return this.AInS;
    }
    
    public void setAInS(Integer AInS) {
        this.AInS = AInS;
    }

    
    @Column(name="a_mr_l", length=5)
    public String getAMrL() {
        return this.AMrL;
    }
    
    public void setAMrL(String AMrL) {
        this.AMrL = AMrL;
    }

    
    @Column(name="a_mr_s")
    public Integer getAMrS() {
        return this.AMrS;
    }
    
    public void setAMrS(Integer AMrS) {
        this.AMrS = AMrS;
    }

    
    @Column(name="a_nf_l", length=5)
    public String getANfL() {
        return this.ANfL;
    }
    
    public void setANfL(String ANfL) {
        this.ANfL = ANfL;
    }

    
    @Column(name="a_nf_s")
    public Integer getANfS() {
        return this.ANfS;
    }
    
    public void setANfS(Integer ANfS) {
        this.ANfS = ANfS;
    }

    
    @Column(name="a_pa_l", length=5)
    public String getAPaL() {
        return this.APaL;
    }
    
    public void setAPaL(String APaL) {
        this.APaL = APaL;
    }

    
    @Column(name="a_pa_s")
    public Integer getAPaS() {
        return this.APaS;
    }
    
    public void setAPaS(Integer APaS) {
        this.APaS = APaS;
    }

    
    @Column(name="a_sa_l", length=5)
    public String getASaL() {
        return this.ASaL;
    }
    
    public void setASaL(String ASaL) {
        this.ASaL = ASaL;
    }

    
    @Column(name="a_sa_s")
    public Integer getASaS() {
        return this.ASaS;
    }
    
    public void setASaS(Integer ASaS) {
        this.ASaS = ASaS;
    }

    
    @Column(name="a_sd_l", length=5)
    public String getASdL() {
        return this.ASdL;
    }
    
    public void setASdL(String ASdL) {
        this.ASdL = ASdL;
    }

    
    @Column(name="a_sd_s")
    public Integer getASdS() {
        return this.ASdS;
    }
    
    public void setASdS(Integer ASdS) {
        this.ASdS = ASdS;
    }

    
    @Column(name="a_ve_l", length=5)
    public String getAVeL() {
        return this.AVeL;
    }
    
    public void setAVeL(String AVeL) {
        this.AVeL = AVeL;
    }

    
    @Column(name="a_ve_s")
    public Integer getAVeS() {
        return this.AVeS;
    }
    
    public void setAVeS(Integer AVeS) {
        this.AVeS = AVeS;
    }

    
    @Column(name="a_vf_l", length=5)
    public String getAVfL() {
        return this.AVfL;
    }
    
    public void setAVfL(String AVfL) {
        this.AVfL = AVfL;
    }

    
    @Column(name="a_vf_s")
    public Integer getAVfS() {
        return this.AVfS;
    }
    
    public void setAVfS(Integer AVfS) {
        this.AVfS = AVfS;
    }

    
    @Column(name="ar_sy", length=9)
    public String getArSy() {
        return this.arSy;
    }
    
    public void setArSy(String arSy) {
        this.arSy = arSy;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="ar_ts", nullable=false, length=19)
    public Date getArTs() {
        return this.arTs;
    }
    
    public void setArTs(Date arTs) {
        this.arTs = arTs;
    }

    
    @Column(name="encouraged", length=200)
    public String getEncouraged() {
        return this.encouraged;
    }
    
    public void setEncouraged(String encouraged) {
        this.encouraged = encouraged;
    }

    
    @Column(name="ep_ag")
    public Integer getEpAg() {
        return this.epAg;
    }
    
    public void setEpAg(Integer epAg) {
        this.epAg = epAg;
    }

    
    @Column(name="ep_ed")
    public Integer getEpEd() {
        return this.epEd;
    }
    
    public void setEpEd(Integer epEd) {
        this.epEd = epEd;
    }

    
    @Column(name="ep_emc")
    public Integer getEpEmc() {
        return this.epEmc;
    }
    
    public void setEpEmc(Integer epEmc) {
        this.epEmc = epEmc;
    }

    
    @Column(name="ep_ha")
    public Integer getEpHa() {
        return this.epHa;
    }
    
    public void setEpHa(Integer epHa) {
        this.epHa = epHa;
    }

    
    @Column(name="ep_hw")
    public Integer getEpHw() {
        return this.epHw;
    }
    
    public void setEpHw(Integer epHw) {
        this.epHw = epHw;
    }

    
    @Column(name="ep_sbl")
    public Integer getEpSbl() {
        return this.epSbl;
    }
    
    public void setEpSbl(Integer epSbl) {
        this.epSbl = epSbl;
    }

    
    @Column(name="ep_sc")
    public Integer getEpSc() {
        return this.epSc;
    }
    
    public void setEpSc(Integer epSc) {
        this.epSc = epSc;
    }

    
    @Column(name="ep_se")
    public Integer getEpSe() {
        return this.epSe;
    }
    
    public void setEpSe(Integer epSe) {
        this.epSe = epSe;
    }

    
    @Column(name="ep_tc")
    public Integer getEpTc() {
        return this.epTc;
    }
    
    public void setEpTc(Integer epTc) {
        this.epTc = epTc;
    }

    
    @Column(name="may_enroll", length=200)
    public String getMayEnroll() {
        return this.mayEnroll;
    }
    
    public void setMayEnroll(String mayEnroll) {
        this.mayEnroll = mayEnroll;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="app_no", nullable=false)
    public ShApplicant getShApplicant() {
        return this.shApplicant;
    }
    
    public void setShApplicant(ShApplicant shApplicant) {
        this.shApplicant = shApplicant;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="test_date", length=10)
    public Date getTestDate() {
        return this.testDate;
    }
    
    public void setTestDate(Date testDate) {
        this.testDate = testDate;
    }




}


