package entity;
// Generated 03 29, 19 5:28:16 PM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Children generated by hbm2java
 */
@Entity
@Table(name="children"
    ,catalog="seniorhighdb"
)
public class Children  implements java.io.Serializable {


     private Long childId;
     private Integer childAge;
     private String childLevel;
     private String childName;
     private String childSchool;
     private Date childTs;
     private ShApplicant shApplicant;

    public Children() {
    }

	
    public Children(Date childTs, ShApplicant shApplicant) {
        this.childTs = childTs;
        this.shApplicant = shApplicant;
    }
    public Children(Integer childAge, String childLevel, String childName, String childSchool, Date childTs, ShApplicant shApplicant) {
       this.childAge = childAge;
       this.childLevel = childLevel;
       this.childName = childName;
       this.childSchool = childSchool;
       this.childTs = childTs;
       this.shApplicant = shApplicant;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="child_id", unique=true, nullable=false)
    public Long getChildId() {
        return this.childId;
    }
    
    public void setChildId(Long childId) {
        this.childId = childId;
    }

    
    @Column(name="child_age")
    public Integer getChildAge() {
        return this.childAge;
    }
    
    public void setChildAge(Integer childAge) {
        this.childAge = childAge;
    }

    
    @Column(name="child_level", length=10)
    public String getChildLevel() {
        return this.childLevel;
    }
    
    public void setChildLevel(String childLevel) {
        this.childLevel = childLevel;
    }

    
    @Column(name="child_name", length=100)
    public String getChildName() {
        return this.childName;
    }
    
    public void setChildName(String childName) {
        this.childName = childName;
    }

    
    @Column(name="child_school", length=150)
    public String getChildSchool() {
        return this.childSchool;
    }
    
    public void setChildSchool(String childSchool) {
        this.childSchool = childSchool;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="child_ts", nullable=false, length=19)
    public Date getChildTs() {
        return this.childTs;
    }
    
    public void setChildTs(Date childTs) {
        this.childTs = childTs;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="app_no", nullable=false)
    public ShApplicant getShApplicant() {
        return this.shApplicant;
    }
    
    public void setShApplicant(ShApplicant shApplicant) {
        this.shApplicant = shApplicant;
    }




}


