package entity;
// Generated 03 29, 19 5:28:16 PM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * ClinicDates generated by hbm2java
 */
@Entity
@Table(name="clinic_dates"
    ,catalog="seniorhighdb"
)
public class ClinicDates  implements java.io.Serializable {


     private Integer clinId;
     private Integer clinAllowed;
     private String clinAmpm;
     private Integer clinCount;
     private Date clinDate;
     private String clinSy;

    public ClinicDates() {
    }

    public ClinicDates(Integer clinAllowed, String clinAmpm, Integer clinCount, Date clinDate, String clinSy) {
       this.clinAllowed = clinAllowed;
       this.clinAmpm = clinAmpm;
       this.clinCount = clinCount;
       this.clinDate = clinDate;
       this.clinSy = clinSy;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="clin_id", unique=true, nullable=false)
    public Integer getClinId() {
        return this.clinId;
    }
    
    public void setClinId(Integer clinId) {
        this.clinId = clinId;
    }

    
    @Column(name="clin_allowed")
    public Integer getClinAllowed() {
        return this.clinAllowed;
    }
    
    public void setClinAllowed(Integer clinAllowed) {
        this.clinAllowed = clinAllowed;
    }

    
    @Column(name="clin_ampm", length=2)
    public String getClinAmpm() {
        return this.clinAmpm;
    }
    
    public void setClinAmpm(String clinAmpm) {
        this.clinAmpm = clinAmpm;
    }

    
    @Column(name="clin_count")
    public Integer getClinCount() {
        return this.clinCount;
    }
    
    public void setClinCount(Integer clinCount) {
        this.clinCount = clinCount;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="clin_date", length=10)
    public Date getClinDate() {
        return this.clinDate;
    }
    
    public void setClinDate(Date clinDate) {
        this.clinDate = clinDate;
    }

    
    @Column(name="clin_sy", length=9)
    public String getClinSy() {
        return this.clinSy;
    }
    
    public void setClinSy(String clinSy) {
        this.clinSy = clinSy;
    }




}


