package entity;
// Generated 03 29, 19 5:28:16 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * CoreValues generated by hbm2java
 */
@Entity
@Table(name="core_values"
    ,catalog="seniorhighdb"
)
public class CoreValues  implements java.io.Serializable {


     private Integer cvId;
     private CoreValuesCategory coreValuesCategory;
     private String description;
     private Set<ShCCorevalues> shCCorevalueses = new HashSet<ShCCorevalues>(0);
     private Date ts;

    public CoreValues() {
    }

	
    public CoreValues(Date ts) {
        this.ts = ts;
    }
    public CoreValues(CoreValuesCategory coreValuesCategory, String description, Set<ShCCorevalues> shCCorevalueses, Date ts) {
       this.coreValuesCategory = coreValuesCategory;
       this.description = description;
       this.shCCorevalueses = shCCorevalueses;
       this.ts = ts;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="cv_id", unique=true, nullable=false)
    public Integer getCvId() {
        return this.cvId;
    }
    
    public void setCvId(Integer cvId) {
        this.cvId = cvId;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="f_cv_catid")
    public CoreValuesCategory getCoreValuesCategory() {
        return this.coreValuesCategory;
    }
    
    public void setCoreValuesCategory(CoreValuesCategory coreValuesCategory) {
        this.coreValuesCategory = coreValuesCategory;
    }

    
    @Column(name="description", length=50)
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="coreValues")
    public Set<ShCCorevalues> getShCCorevalueses() {
        return this.shCCorevalueses;
    }
    
    public void setShCCorevalueses(Set<ShCCorevalues> shCCorevalueses) {
        this.shCCorevalueses = shCCorevalueses;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="ts", nullable=false, length=19)
    public Date getTs() {
        return this.ts;
    }
    
    public void setTs(Date ts) {
        this.ts = ts;
    }




}


