package entity;
// Generated 03 29, 19 5:28:16 PM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * EducAttainmentSibling generated by hbm2java
 */
@Entity
@Table(name="educ_attainment_sibling"
    ,catalog="seniorhighdb"
)
public class EducAttainmentSibling  implements java.io.Serializable {


     private Long easId;
     private ShApplicant shApplicant;
     private String siblingCollege;
     private String siblingHs;
     private String siblingName;
     private Date siblingTs;
     private String siblingYrcourse;

    public EducAttainmentSibling() {
    }

	
    public EducAttainmentSibling(ShApplicant shApplicant, Date siblingTs) {
        this.shApplicant = shApplicant;
        this.siblingTs = siblingTs;
    }
    public EducAttainmentSibling(ShApplicant shApplicant, String siblingCollege, String siblingHs, String siblingName, Date siblingTs, String siblingYrcourse) {
       this.shApplicant = shApplicant;
       this.siblingCollege = siblingCollege;
       this.siblingHs = siblingHs;
       this.siblingName = siblingName;
       this.siblingTs = siblingTs;
       this.siblingYrcourse = siblingYrcourse;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="eas_id", unique=true, nullable=false)
    public Long getEasId() {
        return this.easId;
    }
    
    public void setEasId(Long easId) {
        this.easId = easId;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="app_no", nullable=false)
    public ShApplicant getShApplicant() {
        return this.shApplicant;
    }
    
    public void setShApplicant(ShApplicant shApplicant) {
        this.shApplicant = shApplicant;
    }

    
    @Column(name="sibling_college", length=150)
    public String getSiblingCollege() {
        return this.siblingCollege;
    }
    
    public void setSiblingCollege(String siblingCollege) {
        this.siblingCollege = siblingCollege;
    }

    
    @Column(name="sibling_hs", length=150)
    public String getSiblingHs() {
        return this.siblingHs;
    }
    
    public void setSiblingHs(String siblingHs) {
        this.siblingHs = siblingHs;
    }

    
    @Column(name="sibling_name", length=100)
    public String getSiblingName() {
        return this.siblingName;
    }
    
    public void setSiblingName(String siblingName) {
        this.siblingName = siblingName;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="sibling_ts", nullable=false, length=19)
    public Date getSiblingTs() {
        return this.siblingTs;
    }
    
    public void setSiblingTs(Date siblingTs) {
        this.siblingTs = siblingTs;
    }

    
    @Column(name="sibling_yrcourse", length=100)
    public String getSiblingYrcourse() {
        return this.siblingYrcourse;
    }
    
    public void setSiblingYrcourse(String siblingYrcourse) {
        this.siblingYrcourse = siblingYrcourse;
    }




}


