package entity;
// Generated 03 29, 19 5:28:16 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Honors generated by hbm2java
 */
@Entity
@Table(name="honors"
    ,catalog="seniorhighdb"
)
public class Honors  implements java.io.Serializable {


     private String honor;
     private Short test;

    public Honors() {
    }

	
    public Honors(String honor) {
        this.honor = honor;
    }
    public Honors(String honor, Short test) {
       this.honor = honor;
       this.test = test;
    }
   
     @Id 

    
    @Column(name="honor", unique=true, nullable=false, length=30)
    public String getHonor() {
        return this.honor;
    }
    
    public void setHonor(String honor) {
        this.honor = honor;
    }

    
    @Column(name="test")
    public Short getTest() {
        return this.test;
    }
    
    public void setTest(Short test) {
        this.test = test;
    }




}


