package entity;
// Generated 03 29, 19 5:28:16 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Livingcond generated by hbm2java
 */
@Entity
@Table(name="livingcond"
    ,catalog="seniorhighdb"
)
public class Livingcond  implements java.io.Serializable {


     private String lcond;

    public Livingcond() {
    }

    public Livingcond(String lcond) {
       this.lcond = lcond;
    }
   
     @Id 

    
    @Column(name="lcond", unique=true, nullable=false, length=50)
    public String getLcond() {
        return this.lcond;
    }
    
    public void setLcond(String lcond) {
        this.lcond = lcond;
    }




}


