package entity;
// Generated 03 29, 19 5:28:16 PM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * MonthAttendance generated by hbm2java
 */
@Entity
@Table(name="month_attendance"
    ,catalog="seniorhighdb"
)
public class MonthAttendance  implements java.io.Serializable {


     private Integer monthAttid;
     private Boolean isActive;
     private String monthDays;
     private String months;
     private Integer sem;
     private String sy;
     private Boolean toPrint;
     private Date ts;

    public MonthAttendance() {
    }

	
    public MonthAttendance(Date ts) {
        this.ts = ts;
    }
    public MonthAttendance(Boolean isActive, String monthDays, String months, Integer sem, String sy, Boolean toPrint, Date ts) {
       this.isActive = isActive;
       this.monthDays = monthDays;
       this.months = months;
       this.sem = sem;
       this.sy = sy;
       this.toPrint = toPrint;
       this.ts = ts;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="month_attid", unique=true, nullable=false)
    public Integer getMonthAttid() {
        return this.monthAttid;
    }
    
    public void setMonthAttid(Integer monthAttid) {
        this.monthAttid = monthAttid;
    }

    
    @Column(name="is_active")
    public Boolean getIsActive() {
        return this.isActive;
    }
    
    public void setIsActive(Boolean isActive) {
        this.isActive = isActive;
    }

    
    @Column(name="month_days", length=50)
    public String getMonthDays() {
        return this.monthDays;
    }
    
    public void setMonthDays(String monthDays) {
        this.monthDays = monthDays;
    }

    
    @Column(name="months", length=20)
    public String getMonths() {
        return this.months;
    }
    
    public void setMonths(String months) {
        this.months = months;
    }

    
    @Column(name="sem")
    public Integer getSem() {
        return this.sem;
    }
    
    public void setSem(Integer sem) {
        this.sem = sem;
    }

    
    @Column(name="sy", length=10)
    public String getSy() {
        return this.sy;
    }
    
    public void setSy(String sy) {
        this.sy = sy;
    }

    
    @Column(name="to_print")
    public Boolean getToPrint() {
        return this.toPrint;
    }
    
    public void setToPrint(Boolean toPrint) {
        this.toPrint = toPrint;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="ts", nullable=false, length=19)
    public Date getTs() {
        return this.ts;
    }
    
    public void setTs(Date ts) {
        this.ts = ts;
    }




}


