package entity;
// Generated 03 29, 19 5:28:16 PM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Religions generated by hbm2java
 */
@Entity
@Table(name="religions"
    ,catalog="seniorhighdb"
)
public class Religions  implements java.io.Serializable {


     private String religion;
     private Date religionTs;

    public Religions() {
    }

	
    public Religions(String religion) {
        this.religion = religion;
    }
    public Religions(String religion, Date religionTs) {
       this.religion = religion;
       this.religionTs = religionTs;
    }
   
     @Id 

    
    @Column(name="religion", unique=true, nullable=false, length=30)
    public String getReligion() {
        return this.religion;
    }
    
    public void setReligion(String religion) {
        this.religion = religion;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="religion_ts", length=19)
    public Date getReligionTs() {
        return this.religionTs;
    }
    
    public void setReligionTs(Date religionTs) {
        this.religionTs = religionTs;
    }




}


