package entity;
// Generated 03 29, 19 5:28:16 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * SaLedger generated by hbm2java
 */
@Entity
@Table(name="sa_ledger"
    ,catalog="seniorhighdb"
)
public class SaLedger  implements java.io.Serializable {


     private Long id;
     private BigDecimal credit;
     private BigDecimal debit;
     private String discountcode;
     private String glperiod;
     private String glyear;
     private Boolean iscancel;
     private Boolean isdiscount;
     private Boolean isposted;
     private Boolean isrefund;
     private String itemid;
     private String particular;
     private String receiptdtlid;
     private String reference;
     private String remark;
     private SaLedgerHeader saLedgerHeader;
     private String source;
     private String studentgroup;
     private String studentid;
     private String syear;
     private Date transdate;
     private Date ts;
     private String usercode;

    public SaLedger() {
    }

	
    public SaLedger(BigDecimal credit, BigDecimal debit, String itemid, String reference, String source, String studentgroup, String studentid, String syear, Date transdate, Date ts) {
        this.credit = credit;
        this.debit = debit;
        this.itemid = itemid;
        this.reference = reference;
        this.source = source;
        this.studentgroup = studentgroup;
        this.studentid = studentid;
        this.syear = syear;
        this.transdate = transdate;
        this.ts = ts;
    }
    public SaLedger(BigDecimal credit, BigDecimal debit, String discountcode, String glperiod, String glyear, Boolean iscancel, Boolean isdiscount, Boolean isposted, Boolean isrefund, String itemid, String particular, String receiptdtlid, String reference, String remark, SaLedgerHeader saLedgerHeader, String source, String studentgroup, String studentid, String syear, Date transdate, Date ts, String usercode) {
       this.credit = credit;
       this.debit = debit;
       this.discountcode = discountcode;
       this.glperiod = glperiod;
       this.glyear = glyear;
       this.iscancel = iscancel;
       this.isdiscount = isdiscount;
       this.isposted = isposted;
       this.isrefund = isrefund;
       this.itemid = itemid;
       this.particular = particular;
       this.receiptdtlid = receiptdtlid;
       this.reference = reference;
       this.remark = remark;
       this.saLedgerHeader = saLedgerHeader;
       this.source = source;
       this.studentgroup = studentgroup;
       this.studentid = studentid;
       this.syear = syear;
       this.transdate = transdate;
       this.ts = ts;
       this.usercode = usercode;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }

    
    @Column(name="credit", nullable=false, precision=9, scale=0)
    public BigDecimal getCredit() {
        return this.credit;
    }
    
    public void setCredit(BigDecimal credit) {
        this.credit = credit;
    }

    
    @Column(name="debit", nullable=false, precision=9, scale=0)
    public BigDecimal getDebit() {
        return this.debit;
    }
    
    public void setDebit(BigDecimal debit) {
        this.debit = debit;
    }

    
    @Column(name="discountcode", length=11)
    public String getDiscountcode() {
        return this.discountcode;
    }
    
    public void setDiscountcode(String discountcode) {
        this.discountcode = discountcode;
    }

    
    @Column(name="glperiod", length=2)
    public String getGlperiod() {
        return this.glperiod;
    }
    
    public void setGlperiod(String glperiod) {
        this.glperiod = glperiod;
    }

    
    @Column(name="glyear", length=4)
    public String getGlyear() {
        return this.glyear;
    }
    
    public void setGlyear(String glyear) {
        this.glyear = glyear;
    }

    
    @Column(name="iscancel")
    public Boolean getIscancel() {
        return this.iscancel;
    }
    
    public void setIscancel(Boolean iscancel) {
        this.iscancel = iscancel;
    }

    
    @Column(name="isdiscount")
    public Boolean getIsdiscount() {
        return this.isdiscount;
    }
    
    public void setIsdiscount(Boolean isdiscount) {
        this.isdiscount = isdiscount;
    }

    
    @Column(name="isposted")
    public Boolean getIsposted() {
        return this.isposted;
    }
    
    public void setIsposted(Boolean isposted) {
        this.isposted = isposted;
    }

    
    @Column(name="isrefund")
    public Boolean getIsrefund() {
        return this.isrefund;
    }
    
    public void setIsrefund(Boolean isrefund) {
        this.isrefund = isrefund;
    }

    
    @Column(name="itemid", nullable=false, length=11)
    public String getItemid() {
        return this.itemid;
    }
    
    public void setItemid(String itemid) {
        this.itemid = itemid;
    }

    
    @Column(name="particular", length=150)
    public String getParticular() {
        return this.particular;
    }
    
    public void setParticular(String particular) {
        this.particular = particular;
    }

    
    @Column(name="receiptdtlid", length=40)
    public String getReceiptdtlid() {
        return this.receiptdtlid;
    }
    
    public void setReceiptdtlid(String receiptdtlid) {
        this.receiptdtlid = receiptdtlid;
    }

    
    @Column(name="reference", nullable=false, length=25)
    public String getReference() {
        return this.reference;
    }
    
    public void setReference(String reference) {
        this.reference = reference;
    }

    
    @Column(name="remark")
    public String getRemark() {
        return this.remark;
    }
    
    public void setRemark(String remark) {
        this.remark = remark;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="assessed_id")
    public SaLedgerHeader getSaLedgerHeader() {
        return this.saLedgerHeader;
    }
    
    public void setSaLedgerHeader(SaLedgerHeader saLedgerHeader) {
        this.saLedgerHeader = saLedgerHeader;
    }

    
    @Column(name="source", nullable=false, length=10)
    public String getSource() {
        return this.source;
    }
    
    public void setSource(String source) {
        this.source = source;
    }

    
    @Column(name="studentgroup", nullable=false, length=2)
    public String getStudentgroup() {
        return this.studentgroup;
    }
    
    public void setStudentgroup(String studentgroup) {
        this.studentgroup = studentgroup;
    }

    
    @Column(name="studentid", nullable=false, length=10)
    public String getStudentid() {
        return this.studentid;
    }
    
    public void setStudentid(String studentid) {
        this.studentid = studentid;
    }

    
    @Column(name="syear", nullable=false, length=12)
    public String getSyear() {
        return this.syear;
    }
    
    public void setSyear(String syear) {
        this.syear = syear;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="transdate", nullable=false, length=10)
    public Date getTransdate() {
        return this.transdate;
    }
    
    public void setTransdate(Date transdate) {
        this.transdate = transdate;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="ts", length=19)
    public Date getTs() {
        return this.ts;
    }
    
    public void setTs(Date ts) {
        this.ts = ts;
    }

    
    @Column(name="usercode", length=15)
    public String getUsercode() {
        return this.usercode;
    }
    
    public void setUsercode(String usercode) {
        this.usercode = usercode;
    }




}


