package entity;
// Generated 03 29, 19 5:28:16 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * SaLedgerHeader generated by hbm2java
 */
@Entity
@Table(name="sa_ledger_header"
    ,catalog="seniorhighdb"
)
public class SaLedgerHeader  implements java.io.Serializable {


     private Long id;
     private double assessedAmount;
     private Date assessedTs;
     private String glyear;
     private Set<SaLedger> saLedgers = new HashSet<SaLedger>(0);
     private String schoolyear;
     private String studentgroup;
     private String studentid;
     private Integer yrlevel;

    public SaLedgerHeader() {
    }

	
    public SaLedgerHeader(double assessedAmount, Date assessedTs, String glyear, String schoolyear, String studentgroup, String studentid) {
        this.assessedAmount = assessedAmount;
        this.assessedTs = assessedTs;
        this.glyear = glyear;
        this.schoolyear = schoolyear;
        this.studentgroup = studentgroup;
        this.studentid = studentid;
    }
    public SaLedgerHeader(double assessedAmount, Date assessedTs, String glyear, Set<SaLedger> saLedgers, String schoolyear, String studentgroup, String studentid, Integer yrlevel) {
       this.assessedAmount = assessedAmount;
       this.assessedTs = assessedTs;
       this.glyear = glyear;
       this.saLedgers = saLedgers;
       this.schoolyear = schoolyear;
       this.studentgroup = studentgroup;
       this.studentid = studentid;
       this.yrlevel = yrlevel;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }

    
    @Column(name="assessed_amount", nullable=false, precision=10, scale=0)
    public double getAssessedAmount() {
        return this.assessedAmount;
    }
    
    public void setAssessedAmount(double assessedAmount) {
        this.assessedAmount = assessedAmount;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="assessed_ts", length=19)
    public Date getAssessedTs() {
        return this.assessedTs;
    }
    
    public void setAssessedTs(Date assessedTs) {
        this.assessedTs = assessedTs;
    }

    
    @Column(name="glyear", nullable=false, length=4)
    public String getGlyear() {
        return this.glyear;
    }
    
    public void setGlyear(String glyear) {
        this.glyear = glyear;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="saLedgerHeader")
    public Set<SaLedger> getSaLedgers() {
        return this.saLedgers;
    }
    
    public void setSaLedgers(Set<SaLedger> saLedgers) {
        this.saLedgers = saLedgers;
    }

    
    @Column(name="schoolyear", nullable=false, length=11)
    public String getSchoolyear() {
        return this.schoolyear;
    }
    
    public void setSchoolyear(String schoolyear) {
        this.schoolyear = schoolyear;
    }

    
    @Column(name="studentgroup", nullable=false, length=2)
    public String getStudentgroup() {
        return this.studentgroup;
    }
    
    public void setStudentgroup(String studentgroup) {
        this.studentgroup = studentgroup;
    }

    
    @Column(name="studentid", nullable=false, length=6)
    public String getStudentid() {
        return this.studentid;
    }
    
    public void setStudentid(String studentid) {
        this.studentid = studentid;
    }

    
    @Column(name="yrlevel")
    public Integer getYrlevel() {
        return this.yrlevel;
    }
    
    public void setYrlevel(Integer yrlevel) {
        this.yrlevel = yrlevel;
    }


    

}


