package entity;
// Generated 03 29, 19 5:28:16 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Schoolmonth generated by hbm2java
 */
@Entity
@Table(name="schoolmonth"
    ,catalog="seniorhighdb"
)
public class Schoolmonth  implements java.io.Serializable {


     private String schoolmonth;
     private String monthname;
     private Integer monthnum;
     private Set<ShSchooldays> shSchooldayses = new HashSet<ShSchooldays>(0);

    public Schoolmonth() {
    }

	
    public Schoolmonth(String schoolmonth) {
        this.schoolmonth = schoolmonth;
    }
    public Schoolmonth(String schoolmonth, String monthname, Integer monthnum, Set<ShSchooldays> shSchooldayses) {
       this.schoolmonth = schoolmonth;
       this.monthname = monthname;
       this.monthnum = monthnum;
       this.shSchooldayses = shSchooldayses;
    }
   
     @Id 

    
    @Column(name="schoolmonth", unique=true, nullable=false, length=3)
    public String getSchoolmonth() {
        return this.schoolmonth;
    }
    
    public void setSchoolmonth(String schoolmonth) {
        this.schoolmonth = schoolmonth;
    }

    
    @Column(name="monthname", length=15)
    public String getMonthname() {
        return this.monthname;
    }
    
    public void setMonthname(String monthname) {
        this.monthname = monthname;
    }

    
    @Column(name="monthnum")
    public Integer getMonthnum() {
        return this.monthnum;
    }
    
    public void setMonthnum(Integer monthnum) {
        this.monthnum = monthnum;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="schoolmonth")
    public Set<ShSchooldays> getShSchooldayses() {
        return this.shSchooldayses;
    }
    
    public void setShSchooldayses(Set<ShSchooldays> shSchooldayses) {
        this.shSchooldayses = shSchooldayses;
    }




}


