package entity;
// Generated 03 29, 19 5:28:16 PM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * SchoolAttended generated by hbm2java
 */
@Entity
@Table(name="school_attended"
    ,catalog="seniorhighdb"
)
public class SchoolAttended  implements java.io.Serializable {


     private Long saId;
     private String saAddress;
     private String saFrmyr;
     private String saFrmyrgrade;
     private String saSchool;
     private String saToyr;
     private String saToyrgrade;
     private Date saTs;
     private String saUnitlevel;
     private ShApplicant shApplicant;

    public SchoolAttended() {
    }

	
    public SchoolAttended(Date saTs, ShApplicant shApplicant) {
        this.saTs = saTs;
        this.shApplicant = shApplicant;
    }
    public SchoolAttended(String saAddress, String saFrmyr, String saFrmyrgrade, String saSchool, String saToyr, String saToyrgrade, Date saTs, String saUnitlevel, ShApplicant shApplicant) {
       this.saAddress = saAddress;
       this.saFrmyr = saFrmyr;
       this.saFrmyrgrade = saFrmyrgrade;
       this.saSchool = saSchool;
       this.saToyr = saToyr;
       this.saToyrgrade = saToyrgrade;
       this.saTs = saTs;
       this.saUnitlevel = saUnitlevel;
       this.shApplicant = shApplicant;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="sa_id", unique=true, nullable=false)
    public Long getSaId() {
        return this.saId;
    }
    
    public void setSaId(Long saId) {
        this.saId = saId;
    }

    
    @Column(name="sa_address", length=150)
    public String getSaAddress() {
        return this.saAddress;
    }
    
    public void setSaAddress(String saAddress) {
        this.saAddress = saAddress;
    }

    
    @Column(name="sa_frmyr", length=5)
    public String getSaFrmyr() {
        return this.saFrmyr;
    }
    
    public void setSaFrmyr(String saFrmyr) {
        this.saFrmyr = saFrmyr;
    }

    
    @Column(name="sa_frmyrgrade", length=20)
    public String getSaFrmyrgrade() {
        return this.saFrmyrgrade;
    }
    
    public void setSaFrmyrgrade(String saFrmyrgrade) {
        this.saFrmyrgrade = saFrmyrgrade;
    }

    
    @Column(name="sa_school", length=100)
    public String getSaSchool() {
        return this.saSchool;
    }
    
    public void setSaSchool(String saSchool) {
        this.saSchool = saSchool;
    }

    
    @Column(name="sa_toyr", length=5)
    public String getSaToyr() {
        return this.saToyr;
    }
    
    public void setSaToyr(String saToyr) {
        this.saToyr = saToyr;
    }

    
    @Column(name="sa_toyrgrade", length=20)
    public String getSaToyrgrade() {
        return this.saToyrgrade;
    }
    
    public void setSaToyrgrade(String saToyrgrade) {
        this.saToyrgrade = saToyrgrade;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="sa_ts", nullable=false, length=19)
    public Date getSaTs() {
        return this.saTs;
    }
    
    public void setSaTs(Date saTs) {
        this.saTs = saTs;
    }

    
    @Column(name="sa_unitlevel", length=20)
    public String getSaUnitlevel() {
        return this.saUnitlevel;
    }
    
    public void setSaUnitlevel(String saUnitlevel) {
        this.saUnitlevel = saUnitlevel;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="app_no", nullable=false)
    public ShApplicant getShApplicant() {
        return this.shApplicant;
    }
    
    public void setShApplicant(ShApplicant shApplicant) {
        this.shApplicant = shApplicant;
    }




}


