package entity;
// Generated 03 29, 19 5:28:16 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * ShApplicant generated by hbm2java
 */
@Entity
@Table(name="sh_applicant"
    ,catalog="seniorhighdb"
)
public class ShApplicant  implements java.io.Serializable {


     private String appNo;
     private String appAddress;
     private Byte appAlcoholDrink;
     private String appBarangay;
     private Date appBdate;
     private String appBplace;
     private Byte appChronicMedCond;
     private String appCitizen;
     private String appCity;
     private String appCivStatus;
     private String appContactNo;
     private String appCountry;
     private String appDisabilities;
     private Byte appEcpDecision;
     private String appEcpFinancial;
     private String appEcpMaker;
     private String appEcpOtherpeople;
     private String appEcpReason;
     private String appEcpTypeothers;
     private String appEmeraddress;
     private String appEmeremploymentno;
     private String appEmermobileno;
     private String appEmername;
     private String appEmerrelation;
     private String appEmerresidenceno;
     private String appEthnicAff;
     private String appFailedsubj;
     private String appFamilyStruc;
     private String appFathercollege;
     private String appFathercompany;
     private String appFatherdegree;
     private String appFatheremployer;
     private Boolean appFatherliving;
     private String appFathername;
     private String appFathernaturework;
     private String appFatherposition;
     private String appFatheryear;
     private String appFirstchoice;
     private String appFname;
     private String appGuardian;
     private String appGuardianocc;
     private String appGuidance;
     private String appHeight;
     private String appHonor;
     private String appHospitlized;
     private String appHouseNo;
     private Boolean appInternational;
     private String appJhsGpa;
     private String appJhsSy;
     private String appJuniorhs;
     private String appJuniorhsAddress;
     private String appJuniorsection;
     private String appLanguages;
     private String appLname;
     private String appLrn;
     private String appMedications;
     private Byte appMemoryLapses;
     private String appMi;
     private String appMiddlename;
     private String appMothercollege;
     private String appMothercompany;
     private String appMotherdegree;
     private String appMotheremployer;
     private Boolean appMotherliving;
     private String appMothername;
     private String appMothernaturework;
     private String appMotherposition;
     private String appMotheryear;
     private String appNickname;
     private String appOffenses;
     private String appOrigin;
     private String appParentsStatus;
     private String appPrincipal;
     private Byte appProbAsleep;
     private String appProvince;
     private String appPsycTreatment;
     private String appRelAddress;
     private String appRelContactno;
     private String appRelLivingcond;
     private String appRelName;
     private String appRelRelation;
     private String appReligion;
     private String appRepeatedyr;
     private Set<AppResults> appResultses = new HashSet<AppResults>(0);
     private String appSecondchoice;
     private String appSex;
     private Byte appSmoke;
     private String appSpouseName;
     private String appSpouseOcc;
     private String appStreet;
     private String appSuffix;
     private Byte appSurgery;
     private String appThirdchoice;
     private Date appTs;
     private String appWeight;
     private String appZip;
     private Set<Children> childrens = new HashSet<Children>(0);
     private Set<EducAttainmentSibling> educAttainmentSiblings = new HashSet<EducAttainmentSibling>(0);
     private Byte isarchive;
     private Date lastUpdated;
     private Boolean registrarTag;
     private Set<SchoolAttended> schoolAttendeds = new HashSet<SchoolAttended>(0);
     private String studIdnum;
     private String testingArea;

    public ShApplicant() {
    }

	
    public ShApplicant(String appNo, Date appTs) {
        this.appNo = appNo;
        this.appTs = appTs;
    }
    public ShApplicant(String appNo, String appAddress, Byte appAlcoholDrink, String appBarangay, Date appBdate, String appBplace, Byte appChronicMedCond, String appCitizen, String appCity, String appCivStatus, String appContactNo, String appCountry, String appDisabilities, Byte appEcpDecision, String appEcpFinancial, String appEcpMaker, String appEcpOtherpeople, String appEcpReason, String appEcpTypeothers, String appEmeraddress, String appEmeremploymentno, String appEmermobileno, String appEmername, String appEmerrelation, String appEmerresidenceno, String appEthnicAff, String appFailedsubj, String appFamilyStruc, String appFathercollege, String appFathercompany, String appFatherdegree, String appFatheremployer, Boolean appFatherliving, String appFathername, String appFathernaturework, String appFatherposition, String appFatheryear, String appFirstchoice, String appFname, String appGuardian, String appGuardianocc, String appGuidance, String appHeight, String appHonor, String appHospitlized, String appHouseNo, Boolean appInternational, String appJhsGpa, String appJhsSy, String appJuniorhs, String appJuniorhsAddress, String appJuniorsection, String appLanguages, String appLname, String appLrn, String appMedications, Byte appMemoryLapses, String appMi, String appMiddlename, String appMothercollege, String appMothercompany, String appMotherdegree, String appMotheremployer, Boolean appMotherliving, String appMothername, String appMothernaturework, String appMotherposition, String appMotheryear, String appNickname, String appOffenses, String appOrigin, String appParentsStatus, String appPrincipal, Byte appProbAsleep, String appProvince, String appPsycTreatment, String appRelAddress, String appRelContactno, String appRelLivingcond, String appRelName, String appRelRelation, String appReligion, String appRepeatedyr, Set<AppResults> appResultses, String appSecondchoice, String appSex, Byte appSmoke, String appSpouseName, String appSpouseOcc, String appStreet, String appSuffix, Byte appSurgery, String appThirdchoice, Date appTs, String appWeight, String appZip, Set<Children> childrens, Set<EducAttainmentSibling> educAttainmentSiblings, Byte isarchive, Date lastUpdated, Boolean registrarTag, Set<SchoolAttended> schoolAttendeds, String studIdnum, String testingArea) {
       this.appNo = appNo;
       this.appAddress = appAddress;
       this.appAlcoholDrink = appAlcoholDrink;
       this.appBarangay = appBarangay;
       this.appBdate = appBdate;
       this.appBplace = appBplace;
       this.appChronicMedCond = appChronicMedCond;
       this.appCitizen = appCitizen;
       this.appCity = appCity;
       this.appCivStatus = appCivStatus;
       this.appContactNo = appContactNo;
       this.appCountry = appCountry;
       this.appDisabilities = appDisabilities;
       this.appEcpDecision = appEcpDecision;
       this.appEcpFinancial = appEcpFinancial;
       this.appEcpMaker = appEcpMaker;
       this.appEcpOtherpeople = appEcpOtherpeople;
       this.appEcpReason = appEcpReason;
       this.appEcpTypeothers = appEcpTypeothers;
       this.appEmeraddress = appEmeraddress;
       this.appEmeremploymentno = appEmeremploymentno;
       this.appEmermobileno = appEmermobileno;
       this.appEmername = appEmername;
       this.appEmerrelation = appEmerrelation;
       this.appEmerresidenceno = appEmerresidenceno;
       this.appEthnicAff = appEthnicAff;
       this.appFailedsubj = appFailedsubj;
       this.appFamilyStruc = appFamilyStruc;
       this.appFathercollege = appFathercollege;
       this.appFathercompany = appFathercompany;
       this.appFatherdegree = appFatherdegree;
       this.appFatheremployer = appFatheremployer;
       this.appFatherliving = appFatherliving;
       this.appFathername = appFathername;
       this.appFathernaturework = appFathernaturework;
       this.appFatherposition = appFatherposition;
       this.appFatheryear = appFatheryear;
       this.appFirstchoice = appFirstchoice;
       this.appFname = appFname;
       this.appGuardian = appGuardian;
       this.appGuardianocc = appGuardianocc;
       this.appGuidance = appGuidance;
       this.appHeight = appHeight;
       this.appHonor = appHonor;
       this.appHospitlized = appHospitlized;
       this.appHouseNo = appHouseNo;
       this.appInternational = appInternational;
       this.appJhsGpa = appJhsGpa;
       this.appJhsSy = appJhsSy;
       this.appJuniorhs = appJuniorhs;
       this.appJuniorhsAddress = appJuniorhsAddress;
       this.appJuniorsection = appJuniorsection;
       this.appLanguages = appLanguages;
       this.appLname = appLname;
       this.appLrn = appLrn;
       this.appMedications = appMedications;
       this.appMemoryLapses = appMemoryLapses;
       this.appMi = appMi;
       this.appMiddlename = appMiddlename;
       this.appMothercollege = appMothercollege;
       this.appMothercompany = appMothercompany;
       this.appMotherdegree = appMotherdegree;
       this.appMotheremployer = appMotheremployer;
       this.appMotherliving = appMotherliving;
       this.appMothername = appMothername;
       this.appMothernaturework = appMothernaturework;
       this.appMotherposition = appMotherposition;
       this.appMotheryear = appMotheryear;
       this.appNickname = appNickname;
       this.appOffenses = appOffenses;
       this.appOrigin = appOrigin;
       this.appParentsStatus = appParentsStatus;
       this.appPrincipal = appPrincipal;
       this.appProbAsleep = appProbAsleep;
       this.appProvince = appProvince;
       this.appPsycTreatment = appPsycTreatment;
       this.appRelAddress = appRelAddress;
       this.appRelContactno = appRelContactno;
       this.appRelLivingcond = appRelLivingcond;
       this.appRelName = appRelName;
       this.appRelRelation = appRelRelation;
       this.appReligion = appReligion;
       this.appRepeatedyr = appRepeatedyr;
       this.appResultses = appResultses;
       this.appSecondchoice = appSecondchoice;
       this.appSex = appSex;
       this.appSmoke = appSmoke;
       this.appSpouseName = appSpouseName;
       this.appSpouseOcc = appSpouseOcc;
       this.appStreet = appStreet;
       this.appSuffix = appSuffix;
       this.appSurgery = appSurgery;
       this.appThirdchoice = appThirdchoice;
       this.appTs = appTs;
       this.appWeight = appWeight;
       this.appZip = appZip;
       this.childrens = childrens;
       this.educAttainmentSiblings = educAttainmentSiblings;
       this.isarchive = isarchive;
       this.lastUpdated = lastUpdated;
       this.registrarTag = registrarTag;
       this.schoolAttendeds = schoolAttendeds;
       this.studIdnum = studIdnum;
       this.testingArea = testingArea;
    }
   
     @Id 

    
    @Column(name="app_no", unique=true, nullable=false, length=10)
    public String getAppNo() {
        return this.appNo;
    }
    
    public void setAppNo(String appNo) {
        this.appNo = appNo;
    }

    
    @Column(name="app_address", length=65535)
    public String getAppAddress() {
        return this.appAddress;
    }
    
    public void setAppAddress(String appAddress) {
        this.appAddress = appAddress;
    }

    
    @Column(name="app_alcohol_drink")
    public Byte getAppAlcoholDrink() {
        return this.appAlcoholDrink;
    }
    
    public void setAppAlcoholDrink(Byte appAlcoholDrink) {
        this.appAlcoholDrink = appAlcoholDrink;
    }

    
    @Column(name="app_barangay", length=40)
    public String getAppBarangay() {
        return this.appBarangay;
    }
    
    public void setAppBarangay(String appBarangay) {
        this.appBarangay = appBarangay;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="app_bdate", length=10)
    public Date getAppBdate() {
        return this.appBdate;
    }
    
    public void setAppBdate(Date appBdate) {
        this.appBdate = appBdate;
    }

    
    @Column(name="app_bplace", length=50)
    public String getAppBplace() {
        return this.appBplace;
    }
    
    public void setAppBplace(String appBplace) {
        this.appBplace = appBplace;
    }

    
    @Column(name="app_chronic_med_cond")
    public Byte getAppChronicMedCond() {
        return this.appChronicMedCond;
    }
    
    public void setAppChronicMedCond(Byte appChronicMedCond) {
        this.appChronicMedCond = appChronicMedCond;
    }

    
    @Column(name="app_citizen", length=30)
    public String getAppCitizen() {
        return this.appCitizen;
    }
    
    public void setAppCitizen(String appCitizen) {
        this.appCitizen = appCitizen;
    }

    
    @Column(name="app_city", length=40)
    public String getAppCity() {
        return this.appCity;
    }
    
    public void setAppCity(String appCity) {
        this.appCity = appCity;
    }

    
    @Column(name="app_civ_status", length=30)
    public String getAppCivStatus() {
        return this.appCivStatus;
    }
    
    public void setAppCivStatus(String appCivStatus) {
        this.appCivStatus = appCivStatus;
    }

    
    @Column(name="app_contact_no", length=60)
    public String getAppContactNo() {
        return this.appContactNo;
    }
    
    public void setAppContactNo(String appContactNo) {
        this.appContactNo = appContactNo;
    }

    
    @Column(name="app_country", length=40)
    public String getAppCountry() {
        return this.appCountry;
    }
    
    public void setAppCountry(String appCountry) {
        this.appCountry = appCountry;
    }

    
    @Column(name="app_disabilities", length=100)
    public String getAppDisabilities() {
        return this.appDisabilities;
    }
    
    public void setAppDisabilities(String appDisabilities) {
        this.appDisabilities = appDisabilities;
    }

    
    @Column(name="app_ecp_decision")
    public Byte getAppEcpDecision() {
        return this.appEcpDecision;
    }
    
    public void setAppEcpDecision(Byte appEcpDecision) {
        this.appEcpDecision = appEcpDecision;
    }

    
    @Column(name="app_ecp_financial", length=80)
    public String getAppEcpFinancial() {
        return this.appEcpFinancial;
    }
    
    public void setAppEcpFinancial(String appEcpFinancial) {
        this.appEcpFinancial = appEcpFinancial;
    }

    
    @Column(name="app_ecp_maker", length=80)
    public String getAppEcpMaker() {
        return this.appEcpMaker;
    }
    
    public void setAppEcpMaker(String appEcpMaker) {
        this.appEcpMaker = appEcpMaker;
    }

    
    @Column(name="app_ecp_otherpeople", length=80)
    public String getAppEcpOtherpeople() {
        return this.appEcpOtherpeople;
    }
    
    public void setAppEcpOtherpeople(String appEcpOtherpeople) {
        this.appEcpOtherpeople = appEcpOtherpeople;
    }

    
    @Column(name="app_ecp_reason", length=16777215)
    public String getAppEcpReason() {
        return this.appEcpReason;
    }
    
    public void setAppEcpReason(String appEcpReason) {
        this.appEcpReason = appEcpReason;
    }

    
    @Column(name="app_ecp_typeothers", length=100)
    public String getAppEcpTypeothers() {
        return this.appEcpTypeothers;
    }
    
    public void setAppEcpTypeothers(String appEcpTypeothers) {
        this.appEcpTypeothers = appEcpTypeothers;
    }

    
    @Column(name="app_emeraddress", length=150)
    public String getAppEmeraddress() {
        return this.appEmeraddress;
    }
    
    public void setAppEmeraddress(String appEmeraddress) {
        this.appEmeraddress = appEmeraddress;
    }

    
    @Column(name="app_emeremploymentno", length=60)
    public String getAppEmeremploymentno() {
        return this.appEmeremploymentno;
    }
    
    public void setAppEmeremploymentno(String appEmeremploymentno) {
        this.appEmeremploymentno = appEmeremploymentno;
    }

    
    @Column(name="app_emermobileno", length=60)
    public String getAppEmermobileno() {
        return this.appEmermobileno;
    }
    
    public void setAppEmermobileno(String appEmermobileno) {
        this.appEmermobileno = appEmermobileno;
    }

    
    @Column(name="app_emername", length=80)
    public String getAppEmername() {
        return this.appEmername;
    }
    
    public void setAppEmername(String appEmername) {
        this.appEmername = appEmername;
    }

    
    @Column(name="app_emerrelation", length=60)
    public String getAppEmerrelation() {
        return this.appEmerrelation;
    }
    
    public void setAppEmerrelation(String appEmerrelation) {
        this.appEmerrelation = appEmerrelation;
    }

    
    @Column(name="app_emerresidenceno", length=60)
    public String getAppEmerresidenceno() {
        return this.appEmerresidenceno;
    }
    
    public void setAppEmerresidenceno(String appEmerresidenceno) {
        this.appEmerresidenceno = appEmerresidenceno;
    }

    
    @Column(name="app_ethnic_aff", length=50)
    public String getAppEthnicAff() {
        return this.appEthnicAff;
    }
    
    public void setAppEthnicAff(String appEthnicAff) {
        this.appEthnicAff = appEthnicAff;
    }

    
    @Column(name="app_failedsubj", length=16777215)
    public String getAppFailedsubj() {
        return this.appFailedsubj;
    }
    
    public void setAppFailedsubj(String appFailedsubj) {
        this.appFailedsubj = appFailedsubj;
    }

    
    @Column(name="app_family_struc", length=32)
    public String getAppFamilyStruc() {
        return this.appFamilyStruc;
    }
    
    public void setAppFamilyStruc(String appFamilyStruc) {
        this.appFamilyStruc = appFamilyStruc;
    }

    
    @Column(name="app_fathercollege", length=100)
    public String getAppFathercollege() {
        return this.appFathercollege;
    }
    
    public void setAppFathercollege(String appFathercollege) {
        this.appFathercollege = appFathercollege;
    }

    
    @Column(name="app_fathercompany", length=100)
    public String getAppFathercompany() {
        return this.appFathercompany;
    }
    
    public void setAppFathercompany(String appFathercompany) {
        this.appFathercompany = appFathercompany;
    }

    
    @Column(name="app_fatherdegree", length=100)
    public String getAppFatherdegree() {
        return this.appFatherdegree;
    }
    
    public void setAppFatherdegree(String appFatherdegree) {
        this.appFatherdegree = appFatherdegree;
    }

    
    @Column(name="app_fatheremployer", length=100)
    public String getAppFatheremployer() {
        return this.appFatheremployer;
    }
    
    public void setAppFatheremployer(String appFatheremployer) {
        this.appFatheremployer = appFatheremployer;
    }

    
    @Column(name="app_fatherliving")
    public Boolean getAppFatherliving() {
        return this.appFatherliving;
    }
    
    public void setAppFatherliving(Boolean appFatherliving) {
        this.appFatherliving = appFatherliving;
    }

    
    @Column(name="app_fathername", length=80)
    public String getAppFathername() {
        return this.appFathername;
    }
    
    public void setAppFathername(String appFathername) {
        this.appFathername = appFathername;
    }

    
    @Column(name="app_fathernaturework", length=80)
    public String getAppFathernaturework() {
        return this.appFathernaturework;
    }
    
    public void setAppFathernaturework(String appFathernaturework) {
        this.appFathernaturework = appFathernaturework;
    }

    
    @Column(name="app_fatherposition", length=80)
    public String getAppFatherposition() {
        return this.appFatherposition;
    }
    
    public void setAppFatherposition(String appFatherposition) {
        this.appFatherposition = appFatherposition;
    }

    
    @Column(name="app_fatheryear", length=10)
    public String getAppFatheryear() {
        return this.appFatheryear;
    }
    
    public void setAppFatheryear(String appFatheryear) {
        this.appFatheryear = appFatheryear;
    }

    
    @Column(name="app_firstchoice", length=50)
    public String getAppFirstchoice() {
        return this.appFirstchoice;
    }
    
    public void setAppFirstchoice(String appFirstchoice) {
        this.appFirstchoice = appFirstchoice;
    }

    
    @Column(name="app_fname", length=50)
    public String getAppFname() {
        return this.appFname;
    }
    
    public void setAppFname(String appFname) {
        this.appFname = appFname;
    }

    
    @Column(name="app_guardian", length=80)
    public String getAppGuardian() {
        return this.appGuardian;
    }
    
    public void setAppGuardian(String appGuardian) {
        this.appGuardian = appGuardian;
    }

    
    @Column(name="app_guardianocc", length=80)
    public String getAppGuardianocc() {
        return this.appGuardianocc;
    }
    
    public void setAppGuardianocc(String appGuardianocc) {
        this.appGuardianocc = appGuardianocc;
    }

    
    @Column(name="app_guidance", length=80)
    public String getAppGuidance() {
        return this.appGuidance;
    }
    
    public void setAppGuidance(String appGuidance) {
        this.appGuidance = appGuidance;
    }

    
    @Column(name="app_height", length=10)
    public String getAppHeight() {
        return this.appHeight;
    }
    
    public void setAppHeight(String appHeight) {
        this.appHeight = appHeight;
    }

    
    @Column(name="app_honor", length=50)
    public String getAppHonor() {
        return this.appHonor;
    }
    
    public void setAppHonor(String appHonor) {
        this.appHonor = appHonor;
    }

    
    @Column(name="app_hospitlized", length=16777215)
    public String getAppHospitlized() {
        return this.appHospitlized;
    }
    
    public void setAppHospitlized(String appHospitlized) {
        this.appHospitlized = appHospitlized;
    }

    
    @Column(name="app_house_no", length=20)
    public String getAppHouseNo() {
        return this.appHouseNo;
    }
    
    public void setAppHouseNo(String appHouseNo) {
        this.appHouseNo = appHouseNo;
    }

    
    @Column(name="app_international")
    public Boolean getAppInternational() {
        return this.appInternational;
    }
    
    public void setAppInternational(Boolean appInternational) {
        this.appInternational = appInternational;
    }

    
    @Column(name="app_jhs_gpa", length=5)
    public String getAppJhsGpa() {
        return this.appJhsGpa;
    }
    
    public void setAppJhsGpa(String appJhsGpa) {
        this.appJhsGpa = appJhsGpa;
    }

    
    @Column(name="app_jhs_sy", length=10)
    public String getAppJhsSy() {
        return this.appJhsSy;
    }
    
    public void setAppJhsSy(String appJhsSy) {
        this.appJhsSy = appJhsSy;
    }

    
    @Column(name="app_juniorhs", length=100)
    public String getAppJuniorhs() {
        return this.appJuniorhs;
    }
    
    public void setAppJuniorhs(String appJuniorhs) {
        this.appJuniorhs = appJuniorhs;
    }

    
    @Column(name="app_juniorhs_address", length=65535)
    public String getAppJuniorhsAddress() {
        return this.appJuniorhsAddress;
    }
    
    public void setAppJuniorhsAddress(String appJuniorhsAddress) {
        this.appJuniorhsAddress = appJuniorhsAddress;
    }

    
    @Column(name="app_juniorsection", length=50)
    public String getAppJuniorsection() {
        return this.appJuniorsection;
    }
    
    public void setAppJuniorsection(String appJuniorsection) {
        this.appJuniorsection = appJuniorsection;
    }

    
    @Column(name="app_languages", length=50)
    public String getAppLanguages() {
        return this.appLanguages;
    }
    
    public void setAppLanguages(String appLanguages) {
        this.appLanguages = appLanguages;
    }

    
    @Column(name="app_lname", length=50)
    public String getAppLname() {
        return this.appLname;
    }
    
    public void setAppLname(String appLname) {
        this.appLname = appLname;
    }

    
    @Column(name="app_lrn", length=20)
    public String getAppLrn() {
        return this.appLrn;
    }
    
    public void setAppLrn(String appLrn) {
        this.appLrn = appLrn;
    }

    
    @Column(name="app_medications", length=16777215)
    public String getAppMedications() {
        return this.appMedications;
    }
    
    public void setAppMedications(String appMedications) {
        this.appMedications = appMedications;
    }

    
    @Column(name="app_memory_lapses")
    public Byte getAppMemoryLapses() {
        return this.appMemoryLapses;
    }
    
    public void setAppMemoryLapses(Byte appMemoryLapses) {
        this.appMemoryLapses = appMemoryLapses;
    }

    
    @Column(name="app_mi", length=10)
    public String getAppMi() {
        return this.appMi;
    }
    
    public void setAppMi(String appMi) {
        this.appMi = appMi;
    }

    
    @Column(name="app_middlename", length=50)
    public String getAppMiddlename() {
        return this.appMiddlename;
    }
    
    public void setAppMiddlename(String appMiddlename) {
        this.appMiddlename = appMiddlename;
    }

    
    @Column(name="app_mothercollege", length=100)
    public String getAppMothercollege() {
        return this.appMothercollege;
    }
    
    public void setAppMothercollege(String appMothercollege) {
        this.appMothercollege = appMothercollege;
    }

    
    @Column(name="app_mothercompany", length=100)
    public String getAppMothercompany() {
        return this.appMothercompany;
    }
    
    public void setAppMothercompany(String appMothercompany) {
        this.appMothercompany = appMothercompany;
    }

    
    @Column(name="app_motherdegree", length=100)
    public String getAppMotherdegree() {
        return this.appMotherdegree;
    }
    
    public void setAppMotherdegree(String appMotherdegree) {
        this.appMotherdegree = appMotherdegree;
    }

    
    @Column(name="app_motheremployer", length=100)
    public String getAppMotheremployer() {
        return this.appMotheremployer;
    }
    
    public void setAppMotheremployer(String appMotheremployer) {
        this.appMotheremployer = appMotheremployer;
    }

    
    @Column(name="app_motherliving")
    public Boolean getAppMotherliving() {
        return this.appMotherliving;
    }
    
    public void setAppMotherliving(Boolean appMotherliving) {
        this.appMotherliving = appMotherliving;
    }

    
    @Column(name="app_mothername", length=80)
    public String getAppMothername() {
        return this.appMothername;
    }
    
    public void setAppMothername(String appMothername) {
        this.appMothername = appMothername;
    }

    
    @Column(name="app_mothernaturework", length=80)
    public String getAppMothernaturework() {
        return this.appMothernaturework;
    }
    
    public void setAppMothernaturework(String appMothernaturework) {
        this.appMothernaturework = appMothernaturework;
    }

    
    @Column(name="app_motherposition", length=80)
    public String getAppMotherposition() {
        return this.appMotherposition;
    }
    
    public void setAppMotherposition(String appMotherposition) {
        this.appMotherposition = appMotherposition;
    }

    
    @Column(name="app_motheryear", length=10)
    public String getAppMotheryear() {
        return this.appMotheryear;
    }
    
    public void setAppMotheryear(String appMotheryear) {
        this.appMotheryear = appMotheryear;
    }

    
    @Column(name="app_nickname", length=20)
    public String getAppNickname() {
        return this.appNickname;
    }
    
    public void setAppNickname(String appNickname) {
        this.appNickname = appNickname;
    }

    
    @Column(name="app_offenses", length=16777215)
    public String getAppOffenses() {
        return this.appOffenses;
    }
    
    public void setAppOffenses(String appOffenses) {
        this.appOffenses = appOffenses;
    }

    
    @Column(name="app_origin", length=50)
    public String getAppOrigin() {
        return this.appOrigin;
    }
    
    public void setAppOrigin(String appOrigin) {
        this.appOrigin = appOrigin;
    }

    
    @Column(name="app_parents_status", length=60)
    public String getAppParentsStatus() {
        return this.appParentsStatus;
    }
    
    public void setAppParentsStatus(String appParentsStatus) {
        this.appParentsStatus = appParentsStatus;
    }

    
    @Column(name="app_principal", length=80)
    public String getAppPrincipal() {
        return this.appPrincipal;
    }
    
    public void setAppPrincipal(String appPrincipal) {
        this.appPrincipal = appPrincipal;
    }

    
    @Column(name="app_prob_asleep")
    public Byte getAppProbAsleep() {
        return this.appProbAsleep;
    }
    
    public void setAppProbAsleep(Byte appProbAsleep) {
        this.appProbAsleep = appProbAsleep;
    }

    
    @Column(name="app_province", length=60)
    public String getAppProvince() {
        return this.appProvince;
    }
    
    public void setAppProvince(String appProvince) {
        this.appProvince = appProvince;
    }

    
    @Column(name="app_psyc_treatment", length=16777215)
    public String getAppPsycTreatment() {
        return this.appPsycTreatment;
    }
    
    public void setAppPsycTreatment(String appPsycTreatment) {
        this.appPsycTreatment = appPsycTreatment;
    }

    
    @Column(name="app_rel_address", length=100)
    public String getAppRelAddress() {
        return this.appRelAddress;
    }
    
    public void setAppRelAddress(String appRelAddress) {
        this.appRelAddress = appRelAddress;
    }

    
    @Column(name="app_rel_contactno", length=50)
    public String getAppRelContactno() {
        return this.appRelContactno;
    }
    
    public void setAppRelContactno(String appRelContactno) {
        this.appRelContactno = appRelContactno;
    }

    
    @Column(name="app_rel_livingcond", length=60)
    public String getAppRelLivingcond() {
        return this.appRelLivingcond;
    }
    
    public void setAppRelLivingcond(String appRelLivingcond) {
        this.appRelLivingcond = appRelLivingcond;
    }

    
    @Column(name="app_rel_name", length=80)
    public String getAppRelName() {
        return this.appRelName;
    }
    
    public void setAppRelName(String appRelName) {
        this.appRelName = appRelName;
    }

    
    @Column(name="app_rel_relation", length=50)
    public String getAppRelRelation() {
        return this.appRelRelation;
    }
    
    public void setAppRelRelation(String appRelRelation) {
        this.appRelRelation = appRelRelation;
    }

    
    @Column(name="app_religion", length=40)
    public String getAppReligion() {
        return this.appReligion;
    }
    
    public void setAppReligion(String appReligion) {
        this.appReligion = appReligion;
    }

    
    @Column(name="app_repeatedyr", length=20)
    public String getAppRepeatedyr() {
        return this.appRepeatedyr;
    }
    
    public void setAppRepeatedyr(String appRepeatedyr) {
        this.appRepeatedyr = appRepeatedyr;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="shApplicant")
    public Set<AppResults> getAppResultses() {
        return this.appResultses;
    }
    
    public void setAppResultses(Set<AppResults> appResultses) {
        this.appResultses = appResultses;
    }

    
    @Column(name="app_secondchoice", length=50)
    public String getAppSecondchoice() {
        return this.appSecondchoice;
    }
    
    public void setAppSecondchoice(String appSecondchoice) {
        this.appSecondchoice = appSecondchoice;
    }

    
    @Column(name="app_sex", length=2)
    public String getAppSex() {
        return this.appSex;
    }
    
    public void setAppSex(String appSex) {
        this.appSex = appSex;
    }

    
    @Column(name="app_smoke")
    public Byte getAppSmoke() {
        return this.appSmoke;
    }
    
    public void setAppSmoke(Byte appSmoke) {
        this.appSmoke = appSmoke;
    }

    
    @Column(name="app_spouse_name", length=80)
    public String getAppSpouseName() {
        return this.appSpouseName;
    }
    
    public void setAppSpouseName(String appSpouseName) {
        this.appSpouseName = appSpouseName;
    }

    
    @Column(name="app_spouse_occ", length=100)
    public String getAppSpouseOcc() {
        return this.appSpouseOcc;
    }
    
    public void setAppSpouseOcc(String appSpouseOcc) {
        this.appSpouseOcc = appSpouseOcc;
    }

    
    @Column(name="app_street", length=50)
    public String getAppStreet() {
        return this.appStreet;
    }
    
    public void setAppStreet(String appStreet) {
        this.appStreet = appStreet;
    }

    
    @Column(name="app_suffix", length=10)
    public String getAppSuffix() {
        return this.appSuffix;
    }
    
    public void setAppSuffix(String appSuffix) {
        this.appSuffix = appSuffix;
    }

    
    @Column(name="app_surgery")
    public Byte getAppSurgery() {
        return this.appSurgery;
    }
    
    public void setAppSurgery(Byte appSurgery) {
        this.appSurgery = appSurgery;
    }

    
    @Column(name="app_thirdchoice", length=50)
    public String getAppThirdchoice() {
        return this.appThirdchoice;
    }
    
    public void setAppThirdchoice(String appThirdchoice) {
        this.appThirdchoice = appThirdchoice;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="app_ts", nullable=false, length=19)
    public Date getAppTs() {
        return this.appTs;
    }
    
    public void setAppTs(Date appTs) {
        this.appTs = appTs;
    }

    
    @Column(name="app_weight", length=10)
    public String getAppWeight() {
        return this.appWeight;
    }
    
    public void setAppWeight(String appWeight) {
        this.appWeight = appWeight;
    }

    
    @Column(name="app_zip", length=10)
    public String getAppZip() {
        return this.appZip;
    }
    
    public void setAppZip(String appZip) {
        this.appZip = appZip;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="shApplicant")
    public Set<Children> getChildrens() {
        return this.childrens;
    }
    
    public void setChildrens(Set<Children> childrens) {
        this.childrens = childrens;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="shApplicant")
    public Set<EducAttainmentSibling> getEducAttainmentSiblings() {
        return this.educAttainmentSiblings;
    }
    
    public void setEducAttainmentSiblings(Set<EducAttainmentSibling> educAttainmentSiblings) {
        this.educAttainmentSiblings = educAttainmentSiblings;
    }

    
    @Column(name="isarchive")
    public Byte getIsarchive() {
        return this.isarchive;
    }
    
    public void setIsarchive(Byte isarchive) {
        this.isarchive = isarchive;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="last_updated", length=19)
    public Date getLastUpdated() {
        return this.lastUpdated;
    }
    
    public void setLastUpdated(Date lastUpdated) {
        this.lastUpdated = lastUpdated;
    }

    
    @Column(name="registrar_tag")
    public Boolean getRegistrarTag() {
        return this.registrarTag;
    }
    
    public void setRegistrarTag(Boolean registrarTag) {
        this.registrarTag = registrarTag;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="shApplicant")
    public Set<SchoolAttended> getSchoolAttendeds() {
        return this.schoolAttendeds;
    }
    
    public void setSchoolAttendeds(Set<SchoolAttended> schoolAttendeds) {
        this.schoolAttendeds = schoolAttendeds;
    }

    
    @Column(name="stud_idnum", length=10)
    public String getStudIdnum() {
        return this.studIdnum;
    }
    
    public void setStudIdnum(String studIdnum) {
        this.studIdnum = studIdnum;
    }

    
    @Column(name="testing_area", length=8)
    public String getTestingArea() {
        return this.testingArea;
    }
    
    public void setTestingArea(String testingArea) {
        this.testingArea = testingArea;
    }




}


