package entity;
// Generated 03 29, 19 5:28:16 PM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Transient;

/**
 * ShCAttendance generated by hbm2java
 */
@Entity
@Table(name="sh_c_attendance"
    ,catalog="seniorhighdb"
)
public class ShCAttendance  implements java.io.Serializable {


@Id
    @GeneratedValue(strategy=IDENTITY)
    @Column(name="att_classid", unique=true, nullable=false)
     private Integer attClassid;
     @Column(name="att_sem")
     private String attSem;
     @Column(name="att_strand", length=10)
     private String attStrand;
     @Column(name="att_strandgroup", length=5)
     private String attStrandgroup;
     @Column(name="att_sy", length=10)
     private String attSy;
     @Column(name="att_yrlevel", length=2)
     private String attYrlevel;
     @Column(name="month1", length=3)
     private String month1;
     @Column(name="month10", length=3)
     private String month10;
     @Column(name="month11", length=3)
     private String month11;
     @Column(name="month12", length=3)
     private String month12;
     @Column(name="month2", length=3)
     private String month2;
     @Column(name="month3", length=3)
     private String month3;
     @Column(name="month4", length=3)
     private String month4;
     @Column(name="month5", length=3)
     private String month5;
     @Column(name="month6", length=3)
     private String month6;
     @Column(name="month7", length=3)
     private String month7;
     @Column(name="month8", length=3)
     private String month8;
     @Column(name="month9", length=3)
     private String month9;
     @Column(name="stud_idnum", length=6)
     private String studIdnum;
     @Temporal(TemporalType.TIMESTAMP)
     @Column(name="ts", nullable=false, length=19)
     private Date ts;
     
     @Transient
     private String stud_fullname;
     
     @Transient
     private String days_desc;
     
     @Transient
     private String days_total;

    public ShCAttendance() {
    }

	
    public ShCAttendance(Date ts) {
        this.ts = ts;
    }
    public ShCAttendance(String attSem, String attStrand, String attStrandgroup, String attSy, String attYrlevel, String month1, String month10, String month11, String month12, String month2, String month3, String month4, String month5, String month6, String month7, String month8, String month9, String studIdnum, Date ts) {
       this.attSem = attSem;
       this.attStrand = attStrand;
       this.attStrandgroup = attStrandgroup;
       this.attSy = attSy;
       this.attYrlevel = attYrlevel;
       this.month1 = month1;
       this.month10 = month10;
       this.month11 = month11;
       this.month12 = month12;
       this.month2 = month2;
       this.month3 = month3;
       this.month4 = month4;
       this.month5 = month5;
       this.month6 = month6;
       this.month7 = month7;
       this.month8 = month8;
       this.month9 = month9;
       this.studIdnum = studIdnum;
       this.ts = ts;
    }
   
    public Integer getAttClassid() {
        return this.attClassid;
    }
    
    public void setAttClassid(Integer attClassid) {
        this.attClassid = attClassid;
    }

    
    public String getAttSem() {
        return this.attSem;
    }
    
    public void setAttSem(String attSem) {
        this.attSem = attSem;
    }

    
    public String getAttStrand() {
        return this.attStrand;
    }
    
    public void setAttStrand(String attStrand) {
        this.attStrand = attStrand;
    }

    
    public String getAttStrandgroup() {
        return this.attStrandgroup;
    }
    
    public void setAttStrandgroup(String attStrandgroup) {
        this.attStrandgroup = attStrandgroup;
    }

    
    public String getAttSy() {
        return this.attSy;
    }
    
    public void setAttSy(String attSy) {
        this.attSy = attSy;
    }

    
    public String getAttYrlevel() {
        return this.attYrlevel;
    }
    
    public void setAttYrlevel(String attYrlevel) {
        this.attYrlevel = attYrlevel;
    }

    
    public String getMonth1() {
        return this.month1;
    }
    
    public void setMonth1(String month1) {
        this.month1 = month1;
    }

    
    public String getMonth10() {
        return this.month10;
    }
    
    public void setMonth10(String month10) {
        this.month10 = month10;
    }

    
    public String getMonth11() {
        return this.month11;
    }
    
    public void setMonth11(String month11) {
        this.month11 = month11;
    }

    
    public String getMonth12() {
        return this.month12;
    }
    
    public void setMonth12(String month12) {
        this.month12 = month12;
    }

    
    public String getMonth2() {
        return this.month2;
    }
    
    public void setMonth2(String month2) {
        this.month2 = month2;
    }

    
    public String getMonth3() {
        return this.month3;
    }
    
    public void setMonth3(String month3) {
        this.month3 = month3;
    }

    
    public String getMonth4() {
        return this.month4;
    }
    
    public void setMonth4(String month4) {
        this.month4 = month4;
    }

    
    public String getMonth5() {
        return this.month5;
    }
    
    public void setMonth5(String month5) {
        this.month5 = month5;
    }

    
    public String getMonth6() {
        return this.month6;
    }
    
    public void setMonth6(String month6) {
        this.month6 = month6;
    }

    
    public String getMonth7() {
        return this.month7;
    }
    
    public void setMonth7(String month7) {
        this.month7 = month7;
    }

    
    public String getMonth8() {
        return this.month8;
    }
    
    public void setMonth8(String month8) {
        this.month8 = month8;
    }

    
    public String getMonth9() {
        return this.month9;
    }
    
    public void setMonth9(String month9) {
        this.month9 = month9;
    }

    
    public String getStudIdnum() {
        return this.studIdnum;
    }
    
    public void setStudIdnum(String studIdnum) {
        this.studIdnum = studIdnum;
    }

    public Date getTs() {
        return this.ts;
    }
    
    public void setTs(Date ts) {
        this.ts = ts;
    }

    public String getStud_fullname() {
        return stud_fullname;
    }

    public void setStud_fullname(String stud_fullname) {
        this.stud_fullname = stud_fullname;
    }

    public String getDays_desc() {
        return days_desc;
    }

    public void setDays_desc(String days_desc) {
        this.days_desc = days_desc;
    }

    public String getDays_total() {
        return days_total;
    }

    public void setDays_total(String days_total) {
        this.days_total = days_total;
    }




}


