package entity;
// Generated 03 29, 19 5:28:16 PM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * ShCClassStudent generated by hbm2java
 */
@Entity
@Table(name="sh_c_class_student"
    ,catalog="seniorhighdb"
)
public class ShCClassStudent  implements java.io.Serializable {


     private Long cclassId;
     private String csCrsCode;
     private String csEnrolled;
     private String csFinExam;
     private String csFinGrade;
     private String csIdnum;
     private String csMidGrade;
     private String csRemarks;
     private String csSecQtr;
     private String csSection;
     private Integer csSem;
     private String csStrandgroup;
     private String csSy;
     private Integer csYrLevel;
     private Date lastupdated;
     private Boolean tobedeleted;
     private Date ts;

    public ShCClassStudent() {
    }

	
    public ShCClassStudent(Date lastupdated, Date ts) {
        this.lastupdated = lastupdated;
        this.ts = ts;
    }
    public ShCClassStudent(String csCrsCode, String csEnrolled, String csFinExam, String csFinGrade, String csIdnum, String csMidGrade, String csRemarks, String csSecQtr, String csSection, Integer csSem, String csStrandgroup, String csSy, Integer csYrLevel, Date lastupdated, Boolean tobedeleted, Date ts) {
       this.csCrsCode = csCrsCode;
       this.csEnrolled = csEnrolled;
       this.csFinExam = csFinExam;
       this.csFinGrade = csFinGrade;
       this.csIdnum = csIdnum;
       this.csMidGrade = csMidGrade;
       this.csRemarks = csRemarks;
       this.csSecQtr = csSecQtr;
       this.csSection = csSection;
       this.csSem = csSem;
       this.csStrandgroup = csStrandgroup;
       this.csSy = csSy;
       this.csYrLevel = csYrLevel;
       this.lastupdated = lastupdated;
       this.tobedeleted = tobedeleted;
       this.ts = ts;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="cclass_id", unique=true, nullable=false)
    public Long getCclassId() {
        return this.cclassId;
    }
    
    public void setCclassId(Long cclassId) {
        this.cclassId = cclassId;
    }

    
    @Column(name="cs_crs_code", length=15)
    public String getCsCrsCode() {
        return this.csCrsCode;
    }
    
    public void setCsCrsCode(String csCrsCode) {
        this.csCrsCode = csCrsCode;
    }

    
    @Column(name="cs_enrolled", length=3)
    public String getCsEnrolled() {
        return this.csEnrolled;
    }
    
    public void setCsEnrolled(String csEnrolled) {
        this.csEnrolled = csEnrolled;
    }

    
    @Column(name="cs_fin_exam", length=3)
    public String getCsFinExam() {
        return this.csFinExam;
    }
    
    public void setCsFinExam(String csFinExam) {
        this.csFinExam = csFinExam;
    }

    
    @Column(name="cs_fin_grade", length=3)
    public String getCsFinGrade() {
        return this.csFinGrade;
    }
    
    public void setCsFinGrade(String csFinGrade) {
        this.csFinGrade = csFinGrade;
    }

    
    @Column(name="cs_idnum", length=6)
    public String getCsIdnum() {
        return this.csIdnum;
    }
    
    public void setCsIdnum(String csIdnum) {
        this.csIdnum = csIdnum;
    }

    
    @Column(name="cs_mid_grade", length=3)
    public String getCsMidGrade() {
        return this.csMidGrade;
    }
    
    public void setCsMidGrade(String csMidGrade) {
        this.csMidGrade = csMidGrade;
    }

    
    @Column(name="cs_remarks", length=200)
    public String getCsRemarks() {
        return this.csRemarks;
    }
    
    public void setCsRemarks(String csRemarks) {
        this.csRemarks = csRemarks;
    }

    
    @Column(name="cs_sec_qtr", length=3)
    public String getCsSecQtr() {
        return this.csSecQtr;
    }
    
    public void setCsSecQtr(String csSecQtr) {
        this.csSecQtr = csSecQtr;
    }

    
    @Column(name="cs_section", length=3)
    public String getCsSection() {
        return this.csSection;
    }
    
    public void setCsSection(String csSection) {
        this.csSection = csSection;
    }

    
    @Column(name="cs_sem")
    public Integer getCsSem() {
        return this.csSem;
    }
    
    public void setCsSem(Integer csSem) {
        this.csSem = csSem;
    }

    
    @Column(name="cs_strandgroup", length=2)
    public String getCsStrandgroup() {
        return this.csStrandgroup;
    }
    
    public void setCsStrandgroup(String csStrandgroup) {
        this.csStrandgroup = csStrandgroup;
    }

    
    @Column(name="cs_sy", length=9)
    public String getCsSy() {
        return this.csSy;
    }
    
    public void setCsSy(String csSy) {
        this.csSy = csSy;
    }

    
    @Column(name="cs_yr_level")
    public Integer getCsYrLevel() {
        return this.csYrLevel;
    }
    
    public void setCsYrLevel(Integer csYrLevel) {
        this.csYrLevel = csYrLevel;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="lastupdated", nullable=false, length=19)
    public Date getLastupdated() {
        return this.lastupdated;
    }
    
    public void setLastupdated(Date lastupdated) {
        this.lastupdated = lastupdated;
    }

    
    @Column(name="tobedeleted")
    public Boolean getTobedeleted() {
        return this.tobedeleted;
    }
    
    public void setTobedeleted(Boolean tobedeleted) {
        this.tobedeleted = tobedeleted;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="ts", nullable=false, length=19)
    public Date getTs() {
        return this.ts;
    }
    
    public void setTs(Date ts) {
        this.ts = ts;
    }




}


