package entity;
// Generated 03 29, 19 5:28:16 PM by Hibernate Tools 4.3.1


import java.util.Date;
import javafx.beans.property.SimpleStringProperty;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Transient;
import org.hibernate.annotations.GenericGenerator;

/**
 * ShCClassStud generated by hbm2java
 */
@Entity
@Table(name="sh_c_class_stud"
    ,catalog="seniorhighdb"
)
public class ShCClassStud  implements java.io.Serializable {


@Id
    @Column(name="cclass_id", unique=true, nullable=false, length=20)
     private String cclassId;
     @Column(name="cs_crs_code", length=15)
     private String csCrsCode;
     @Column(name="cs_enrolled", length=3)
     private String csEnrolled;
     @Column(name="cs_fin_exam", length=3)
     private String csFinExam;
     @Column(name="cs_fin_grade", length=3)
     private String csFinGrade;
     @Column(name="cs_idnum", length=6)
     private String csIdnum;
     @Column(name="cs_mid_grade", length=3)
     private String csMidGrade;
     @Column(name="cs_remarks", length=200)
     private String csRemarks;
     @Column(name="cs_sec_qtr", length=3)
     private String csSecQtr;
     @Column(name="cs_section", length=3)
     private String csSection;
     @Column(name="cs_sem")
     private Integer csSem;
     @Column(name="cs_strandgroup", length=3)
     private String csStrandgroup;
     @Column(name="cs_sy", length=9)
     private String csSy;
     @Column(name="cs_yr_level")
     private Integer csYrLevel;
     @Temporal(TemporalType.TIMESTAMP)
     @Column(name="lastupdated", insertable=false, updatable=false, length=19)
     private Date lastupdated;
     @Column(name="tobedeleted")
     private Boolean tobedeleted;
     @Temporal(TemporalType.TIMESTAMP)
     @Column(name="ts", insertable=false, updatable=false, length=19)
     private Date ts;
     
     @Transient
     private SimpleStringProperty stud_fullname = new SimpleStringProperty();
     
     @Transient
     private SimpleStringProperty stud_section = new SimpleStringProperty();
     
     @Transient
     private SimpleStringProperty strand_code = new SimpleStringProperty();
     
     @Transient
     private SimpleStringProperty subject_desc = new SimpleStringProperty();
     
     @Transient
     private SimpleStringProperty subject_type = new SimpleStringProperty();

     @Transient
     private SimpleStringProperty subject_unit = new SimpleStringProperty();
     
     @Transient
     private SimpleStringProperty subject_room_daytime_list = new SimpleStringProperty();
     
     @Transient
     private SimpleStringProperty class_section = new SimpleStringProperty();
     
     @Transient
     private SimpleStringProperty class_teacher_name = new SimpleStringProperty();
     
     @Transient
     private SimpleStringProperty room = new SimpleStringProperty();
     
     @Transient
     private SimpleStringProperty day_assigned = new SimpleStringProperty();
     
     @Transient
     private SimpleStringProperty time_start = new SimpleStringProperty();
     
     @Transient
     private SimpleStringProperty time_end = new SimpleStringProperty();
     
     @Transient
     private SimpleStringProperty class_info_id = new SimpleStringProperty();
     
     @Transient
     private SimpleStringProperty subject_gradelevel = new SimpleStringProperty();
     
     @Transient
     private SimpleStringProperty subject_fg = new SimpleStringProperty();
     
     

    public ShCClassStud() {
    }

	
    public ShCClassStud(String cclassId) {
        this.cclassId = cclassId;
    }
    public ShCClassStud(String cclassId, String csCrsCode, String csEnrolled, String csFinExam, String csFinGrade, String csIdnum, String csMidGrade, String csRemarks, String csSecQtr, String csSection, Integer csSem, String csStrandgroup, String csSy, Integer csYrLevel, Date lastupdated, Boolean tobedeleted, Date ts) {
       this.cclassId = cclassId;
       this.csCrsCode = csCrsCode;
       this.csEnrolled = csEnrolled;
       this.csFinExam = csFinExam;
       this.csFinGrade = csFinGrade;
       this.csIdnum = csIdnum;
       this.csMidGrade = csMidGrade;
       this.csRemarks = csRemarks;
       this.csSecQtr = csSecQtr;
       this.csSection = csSection;
       this.csSem = csSem;
       this.csStrandgroup = csStrandgroup;
       this.csSy = csSy;
       this.csYrLevel = csYrLevel;
       this.lastupdated = lastupdated;
       this.tobedeleted = tobedeleted;
       this.ts = ts;
    }
   
    public String getCclassId() {
        return this.cclassId;
    }
    
    public void setCclassId(String cclassId) {
        this.cclassId = cclassId;
    }

    
    public String getCsCrsCode() {
        return this.csCrsCode;
    }
    
    public void setCsCrsCode(String csCrsCode) {
        this.csCrsCode = csCrsCode;
    }

    
    public String getCsEnrolled() {
        return this.csEnrolled;
    }
    
    public void setCsEnrolled(String csEnrolled) {
        this.csEnrolled = csEnrolled;
    }

    
    public String getCsFinExam() {
        return this.csFinExam;
    }
    
    public void setCsFinExam(String csFinExam) {
        this.csFinExam = csFinExam;
    }

    
    public String getCsFinGrade() {
        return this.csFinGrade;
    }
    
    public void setCsFinGrade(String csFinGrade) {
        this.csFinGrade = csFinGrade;
    }

    
    public String getCsIdnum() {
        return this.csIdnum;
    }
    
    public void setCsIdnum(String csIdnum) {
        this.csIdnum = csIdnum;
    }

    
    public String getCsMidGrade() {
        return this.csMidGrade;
    }
    
    public void setCsMidGrade(String csMidGrade) {
        this.csMidGrade = csMidGrade;
    }

    
    public String getCsRemarks() {
        return this.csRemarks;
    }
    
    public void setCsRemarks(String csRemarks) {
        this.csRemarks = csRemarks;
    }

    
    public String getCsSecQtr() {
        return this.csSecQtr;
    }
    
    public void setCsSecQtr(String csSecQtr) {
        this.csSecQtr = csSecQtr;
    }

    
    public String getCsSection() {
        return this.csSection;
    }
    
    public void setCsSection(String csSection) {
        this.csSection = csSection;
    }

    
    public Integer getCsSem() {
        return this.csSem;
    }
    
    public void setCsSem(Integer csSem) {
        this.csSem = csSem;
    }

    
    public String getCsStrandgroup() {
        return this.csStrandgroup;
    }
    
    public void setCsStrandgroup(String csStrandgroup) {
        this.csStrandgroup = csStrandgroup;
    }

    
    public String getCsSy() {
        return this.csSy;
    }
    
    public void setCsSy(String csSy) {
        this.csSy = csSy;
    }

    
    public Integer getCsYrLevel() {
        return this.csYrLevel;
    }
    
    public void setCsYrLevel(Integer csYrLevel) {
        this.csYrLevel = csYrLevel;
    }

    public Date getLastupdated() {
        return this.lastupdated;
    }
    
    public void setLastupdated(Date lastupdated) {
        this.lastupdated = lastupdated;
    }

    
    public Boolean getTobedeleted() {
        return this.tobedeleted;
    }
    
    public void setTobedeleted(Boolean tobedeleted) {
        this.tobedeleted = tobedeleted;
    }

    public Date getTs() {
        return this.ts;
    }
    
    public void setTs(Date ts) {
        this.ts = ts;
    }

    public String getStud_fullname() {
        return stud_fullname.get();
    }

    public void setStud_fullname(String stud_fullname) {
        this.stud_fullname.set(stud_fullname);
    }
    
    public String getStud_section() {
        return stud_section.get();
    }

    public void setStud_section(String stud_section) {
        this.stud_section.set(stud_section);
    }
    
    public String getStrand_code() {
        return strand_code.get();
    }

    public void setStrand_code(String strand_code) {
        this.strand_code.set(strand_code);
    }
    
    public String getSubject_desc() {
        return subject_desc.get();
    }

    public void setSubject_desc(String subject_desc) {
        this.subject_desc.set(subject_desc);
    }
    
     public String getSubject_type() {
        return subject_type.get();
    }

    public void setSubject_type(String subject_type) {
        this.subject_type.set(subject_type);
    }
    
    public String getSubject_unit() {
        return subject_unit.get();
    }

    public void setSubject_unit(String subject_unit) {
        this.subject_unit.set(subject_unit);
    }
    
    public String getSubject_room_daytime_list() {
        return subject_room_daytime_list.get();
    }

    public void setSubject_room_daytime_list(String subject_room_daytime_list) {
        this.subject_room_daytime_list.set(subject_room_daytime_list);
    }
    
    public String getClass_section() {
        return class_section.get();
    }

    public void setClass_section(String class_section) {
        this.class_section.set(class_section);
    }
    
     public String getClass_teacher_name() {
        return class_teacher_name.get();
    }

    public void setClass_teacher_name(String class_teacher_name) {
        this.class_teacher_name.set(class_teacher_name);;
    }  
    
    public String getRoom() {
        return room.get();
    }

    public void setRoom(String room) {
        this.room.set(room);
    }
    
    public String getDay_assigned() {
        return day_assigned.get();
    }

    public void setDay_assigned(String day_assigned) {
        this.day_assigned.set(day_assigned);
    }
    
    public String getTime_start() {
        return time_start.get();
    }

    public void setTime_start(String time_start) {
        this.time_start.set(time_start);
    }
    
    public String getTime_end() {
        return time_end.get();
    }

    public void setTime_end(String time_end) {
        this.time_end.set(time_end);
    }

    public String getClass_info_id() {
        return class_info_id.get();
    }

    public void setClass_info_id(String class_info_id) {
        this.class_info_id.set(class_info_id);
    }
    
    public String getSubject_gradelevel() {
        return subject_gradelevel.get();
    }

    public void setSubject_gradelevel(String subject_gradelevel) {
        this.subject_gradelevel.set(subject_gradelevel);
    }
    
    public String getSubject_fg() {
        return subject_fg.get();
    }

    public void setSubject_fg(String subject_fg) {
        this.subject_fg.set(subject_fg);
    }
}


