package entity;
// Generated 03 29, 19 5:28:16 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * ShCourseSysemTemp generated by hbm2java
 */
@Entity
@Table(name="sh_course_sysem_temp"
    ,catalog="seniorhighdb"
)
public class ShCourseSysemTemp  implements java.io.Serializable {


     private Integer id;
     private String crsCode;
     private String crsTitle;
     private BigDecimal crsUnits;
     private String gradeLevel;
     private String preCrsCode;
     private String strandCodes;
     private String strandSem;
     private String strandSy;
     private String subjType;
     private Date ts;
     private Integer withLab;

    public ShCourseSysemTemp() {
    }

	
    public ShCourseSysemTemp(Date ts) {
        this.ts = ts;
    }
    public ShCourseSysemTemp(String crsCode, String crsTitle, BigDecimal crsUnits, String gradeLevel, String preCrsCode, String strandCodes, String strandSem, String strandSy, String subjType, Date ts, Integer withLab) {
       this.crsCode = crsCode;
       this.crsTitle = crsTitle;
       this.crsUnits = crsUnits;
       this.gradeLevel = gradeLevel;
       this.preCrsCode = preCrsCode;
       this.strandCodes = strandCodes;
       this.strandSem = strandSem;
       this.strandSy = strandSy;
       this.subjType = subjType;
       this.ts = ts;
       this.withLab = withLab;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    
    @Column(name="crs_code", length=10)
    public String getCrsCode() {
        return this.crsCode;
    }
    
    public void setCrsCode(String crsCode) {
        this.crsCode = crsCode;
    }

    
    @Column(name="crs_title", length=200)
    public String getCrsTitle() {
        return this.crsTitle;
    }
    
    public void setCrsTitle(String crsTitle) {
        this.crsTitle = crsTitle;
    }

    
    @Column(name="crs_units", precision=5, scale=0)
    public BigDecimal getCrsUnits() {
        return this.crsUnits;
    }
    
    public void setCrsUnits(BigDecimal crsUnits) {
        this.crsUnits = crsUnits;
    }

    
    @Column(name="grade_level", length=5)
    public String getGradeLevel() {
        return this.gradeLevel;
    }
    
    public void setGradeLevel(String gradeLevel) {
        this.gradeLevel = gradeLevel;
    }

    
    @Column(name="pre_crs_code", length=10)
    public String getPreCrsCode() {
        return this.preCrsCode;
    }
    
    public void setPreCrsCode(String preCrsCode) {
        this.preCrsCode = preCrsCode;
    }

    
    @Column(name="strand_codes", length=40)
    public String getStrandCodes() {
        return this.strandCodes;
    }
    
    public void setStrandCodes(String strandCodes) {
        this.strandCodes = strandCodes;
    }

    
    @Column(name="strand_sem", length=10)
    public String getStrandSem() {
        return this.strandSem;
    }
    
    public void setStrandSem(String strandSem) {
        this.strandSem = strandSem;
    }

    
    @Column(name="strand_sy", length=10)
    public String getStrandSy() {
        return this.strandSy;
    }
    
    public void setStrandSy(String strandSy) {
        this.strandSy = strandSy;
    }

    
    @Column(name="subj_type", length=50)
    public String getSubjType() {
        return this.subjType;
    }
    
    public void setSubjType(String subjType) {
        this.subjType = subjType;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="ts", nullable=false, length=19)
    public Date getTs() {
        return this.ts;
    }
    
    public void setTs(Date ts) {
        this.ts = ts;
    }

    
    @Column(name="with_lab")
    public Integer getWithLab() {
        return this.withLab;
    }
    
    public void setWithLab(Integer withLab) {
        this.withLab = withLab;
    }




}


