package entity;
// Generated 03 29, 19 5:28:16 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * ShCourse generated by hbm2java
 */
@Entity
@Table(name="sh_course"
    ,catalog="seniorhighdb"
)
public class ShCourse  implements java.io.Serializable {


     private String crsCode;
     private Boolean active;
     private String crsDescription;
     private String crsTitle;
     private Date crsTs;
     private Boolean crsType;
     private BigDecimal crsUnits;
     private Byte locked;
     private Boolean tor;
     private Byte wpa;

    public ShCourse() {
    }

	
    public ShCourse(String crsCode, Date crsTs) {
        this.crsCode = crsCode;
        this.crsTs = crsTs;
    }
    public ShCourse(String crsCode, Boolean active, String crsDescription, String crsTitle, Date crsTs, Boolean crsType, BigDecimal crsUnits, Byte locked, Boolean tor, Byte wpa) {
       this.crsCode = crsCode;
       this.active = active;
       this.crsDescription = crsDescription;
       this.crsTitle = crsTitle;
       this.crsTs = crsTs;
       this.crsType = crsType;
       this.crsUnits = crsUnits;
       this.locked = locked;
       this.tor = tor;
       this.wpa = wpa;
    }
   
     @Id 

    
    @Column(name="crs_code", unique=true, nullable=false, length=15)
    public String getCrsCode() {
        return this.crsCode;
    }
    
    public void setCrsCode(String crsCode) {
        this.crsCode = crsCode;
    }

    
    @Column(name="active")
    public Boolean getActive() {
        return this.active;
    }
    
    public void setActive(Boolean active) {
        this.active = active;
    }

    
    @Column(name="crs_description", length=65535)
    public String getCrsDescription() {
        return this.crsDescription;
    }
    
    public void setCrsDescription(String crsDescription) {
        this.crsDescription = crsDescription;
    }

    
    @Column(name="crs_title", length=150)
    public String getCrsTitle() {
        return this.crsTitle;
    }
    
    public void setCrsTitle(String crsTitle) {
        this.crsTitle = crsTitle;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="crs_ts", nullable=false, length=19)
    public Date getCrsTs() {
        return this.crsTs;
    }
    
    public void setCrsTs(Date crsTs) {
        this.crsTs = crsTs;
    }

    
    @Column(name="crs_type")
    public Boolean getCrsType() {
        return this.crsType;
    }
    
    public void setCrsType(Boolean crsType) {
        this.crsType = crsType;
    }

    
    @Column(name="crs_units", precision=5, scale=0)
    public BigDecimal getCrsUnits() {
        return this.crsUnits;
    }
    
    public void setCrsUnits(BigDecimal crsUnits) {
        this.crsUnits = crsUnits;
    }

    
    @Column(name="locked")
    public Byte getLocked() {
        return this.locked;
    }
    
    public void setLocked(Byte locked) {
        this.locked = locked;
    }

    
    @Column(name="tor")
    public Boolean getTor() {
        return this.tor;
    }
    
    public void setTor(Boolean tor) {
        this.tor = tor;
    }

    
    @Column(name="wpa")
    public Byte getWpa() {
        return this.wpa;
    }
    
    public void setWpa(Byte wpa) {
        this.wpa = wpa;
    }




}


