package entity;
// Generated 03 29, 19 5:28:16 PM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * ShConfirmation generated by hbm2java
 */
@Entity
@Table(name="sh_confirmation"
    ,catalog="seniorhighdb"
)
public class ShConfirmation  implements java.io.Serializable {


     private Long confirmId;
     private String clinicAmpm;
     private Date clinicDate;
     private Date clinicDateValid;
     private Boolean clinicValidated;
     private String conSy;
     private Date conTs;
     private Date confirmDate;
     private Boolean confirmed;
     private Boolean reqBc;
     private Boolean reqGmc;
     private Boolean reqOrc;
     private Boolean reqPact;
     private Boolean reqPrc;
     private ShApplicant shApplicant;
     private String strandCode;
     private String strandGroup;
     private String studentId;

    public ShConfirmation() {
    }

    public ShConfirmation(String clinicAmpm, Date clinicDate, Date clinicDateValid, Boolean clinicValidated, String conSy, Date conTs, Date confirmDate, Boolean confirmed, Boolean reqBc, Boolean reqGmc, Boolean reqOrc, Boolean reqPact, Boolean reqPrc, ShApplicant shApplicant, String strandCode, String strandGroup, String studentId) {
       this.clinicAmpm = clinicAmpm;
       this.clinicDate = clinicDate;
       this.clinicDateValid = clinicDateValid;
       this.clinicValidated = clinicValidated;
       this.conSy = conSy;
       this.conTs = conTs;
       this.confirmDate = confirmDate;
       this.confirmed = confirmed;
       this.reqBc = reqBc;
       this.reqGmc = reqGmc;
       this.reqOrc = reqOrc;
       this.reqPact = reqPact;
       this.reqPrc = reqPrc;
       this.shApplicant = shApplicant;
       this.strandCode = strandCode;
       this.strandGroup = strandGroup;
       this.studentId = studentId;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="confirm_id", unique=true, nullable=false)
    public Long getConfirmId() {
        return this.confirmId;
    }
    
    public void setConfirmId(Long confirmId) {
        this.confirmId = confirmId;
    }

    
    @Column(name="clinic_ampm", length=2)
    public String getClinicAmpm() {
        return this.clinicAmpm;
    }
    
    public void setClinicAmpm(String clinicAmpm) {
        this.clinicAmpm = clinicAmpm;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="clinic_date", length=10)
    public Date getClinicDate() {
        return this.clinicDate;
    }
    
    public void setClinicDate(Date clinicDate) {
        this.clinicDate = clinicDate;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="clinic_date_valid", length=10)
    public Date getClinicDateValid() {
        return this.clinicDateValid;
    }
    
    public void setClinicDateValid(Date clinicDateValid) {
        this.clinicDateValid = clinicDateValid;
    }

    
    @Column(name="clinic_validated")
    public Boolean getClinicValidated() {
        return this.clinicValidated;
    }
    
    public void setClinicValidated(Boolean clinicValidated) {
        this.clinicValidated = clinicValidated;
    }

    
    @Column(name="con_sy", length=9)
    public String getConSy() {
        return this.conSy;
    }
    
    public void setConSy(String conSy) {
        this.conSy = conSy;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="con_ts", insertable=false, length=19)
    public Date getConTs() {
        return this.conTs;
    }
    
    public void setConTs(Date conTs) {
        this.conTs = conTs;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="confirm_date", length=10)
    public Date getConfirmDate() {
        return this.confirmDate;
    }
    
    public void setConfirmDate(Date confirmDate) {
        this.confirmDate = confirmDate;
    }

    
    @Column(name="confirmed")
    public Boolean getConfirmed() {
        return this.confirmed;
    }
    
    public void setConfirmed(Boolean confirmed) {
        this.confirmed = confirmed;
    }

    
    @Column(name="req_bc")
    public Boolean getReqBc() {
        return this.reqBc;
    }
    
    public void setReqBc(Boolean reqBc) {
        this.reqBc = reqBc;
    }

    
    @Column(name="req_gmc")
    public Boolean getReqGmc() {
        return this.reqGmc;
    }
    
    public void setReqGmc(Boolean reqGmc) {
        this.reqGmc = reqGmc;
    }

    
    @Column(name="req_orc")
    public Boolean getReqOrc() {
        return this.reqOrc;
    }
    
    public void setReqOrc(Boolean reqOrc) {
        this.reqOrc = reqOrc;
    }

    
    @Column(name="req_pact")
    public Boolean getReqPact() {
        return this.reqPact;
    }
    
    public void setReqPact(Boolean reqPact) {
        this.reqPact = reqPact;
    }

    
    @Column(name="req_prc")
    public Boolean getReqPrc() {
        return this.reqPrc;
    }
    
    public void setReqPrc(Boolean reqPrc) {
        this.reqPrc = reqPrc;
    }

    @ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="app_no", nullable=false)
    public ShApplicant getShApplicant() {
        return this.shApplicant;
    }
    
    public void setShApplicant(ShApplicant shApplicant) {
        this.shApplicant = shApplicant;
    }

    
    @Column(name="strand_code", length=20)
    public String getStrandCode() {
        return this.strandCode;
    }
    
    public void setStrandCode(String strandCode) {
        this.strandCode = strandCode;
    }

    
    @Column(name="strand_group", length=1)
    public String getStrandGroup() {
        return this.strandGroup;
    }
    
    public void setStrandGroup(String strandGroup) {
        this.strandGroup = strandGroup;
    }

    
    @Column(name="student_id", length=10)
    public String getStudentId() {
        return this.studentId;
    }
    
    public void setStudentId(String studentId) {
        this.studentId = studentId;
    }




}


