package entity;
// Generated 03 29, 19 5:28:16 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * ShCourseList generated by hbm2java
 */
@Entity
@Table(name="sh_course_list"
    ,catalog="seniorhighdb"
)
public class ShCourseList  implements java.io.Serializable {


     private Integer crsId;
     private String crsCode;
     private String crsTitle;
     private String crsType;
     private Integer is_no_grade;
     private Integer is_class_basis;
     private BigDecimal crsUnit;
     private Date dateCreated;
     private String preCrsCode;
     private Set<ShCurrDtl> shCurrDtls = new HashSet<ShCurrDtl>(0);
     private Date ts;
     private Integer withLab;

    public ShCourseList() {
    }

	
    public ShCourseList(Date ts) {
        this.ts = ts;
    }
    public ShCourseList(String crsCode, String crsTitle, String crsType, BigDecimal crsUnit, Date dateCreated, String preCrsCode, Set<ShCurrDtl> shCurrDtls, Date ts, Integer withLab) {
       this.crsCode = crsCode;
       this.crsTitle = crsTitle;
       this.crsType = crsType;
       this.crsUnit = crsUnit;
       this.dateCreated = dateCreated;
       this.preCrsCode = preCrsCode;
       this.shCurrDtls = shCurrDtls;
       this.ts = ts;
       this.withLab = withLab;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="crs_id", unique=true, nullable=false)
    public Integer getCrsId() {
        return this.crsId;
    }
    
    public void setCrsId(Integer crsId) {
        this.crsId = crsId;
    }

    
    @Column(name="crs_code", length=10)
    public String getCrsCode() {
        return this.crsCode;
    }
    
    public void setCrsCode(String crsCode) {
        this.crsCode = crsCode;
    }

    
    @Column(name="crs_title", length=200)
    public String getCrsTitle() {
        return this.crsTitle;
    }
    
    public void setCrsTitle(String crsTitle) {
        this.crsTitle = crsTitle;
    }

    
    @Column(name="crs_type", length=50)
    public String getCrsType() {
        return this.crsType;
    }
    
    public void setCrsType(String crsType) {
        this.crsType = crsType;
    }

    
    @Column(name="crs_unit", precision=5, scale=0)
    public BigDecimal getCrsUnit() {
        return this.crsUnit;
    }
    
    public void setCrsUnit(BigDecimal crsUnit) {
        this.crsUnit = crsUnit;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="date_created", length=19)
    public Date getDateCreated() {
        return this.dateCreated;
    }
    
    public void setDateCreated(Date dateCreated) {
        this.dateCreated = dateCreated;
    }

    
    @Column(name="pre_crs_code", length=10)
    public String getPreCrsCode() {
        return this.preCrsCode;
    }
    
    public void setPreCrsCode(String preCrsCode) {
        this.preCrsCode = preCrsCode;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="shCourseList")
    public Set<ShCurrDtl> getShCurrDtls() {
        return this.shCurrDtls;
    }
    
    public void setShCurrDtls(Set<ShCurrDtl> shCurrDtls) {
        this.shCurrDtls = shCurrDtls;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="ts", insertable=false, updatable=false, length=19)
    public Date getTs() {
        return this.ts;
    }
    
    public void setTs(Date ts) {
        this.ts = ts;
    }

    
    @Column(name="with_lab")
    public Integer getWithLab() {
        return this.withLab;
    }
    
    public void setWithLab(Integer withLab) {
        this.withLab = withLab;
    }

    public Integer getIs_no_grade() {
        return is_no_grade;
    }

    public void setIs_no_grade(Integer is_no_grade) {
        this.is_no_grade = is_no_grade;
    }

    public Integer getIs_class_basis() {
        return is_class_basis;
    }

    public void setIs_class_basis(Integer is_class_basis) {
        this.is_class_basis = is_class_basis;
    }




}


