package entity;
// Generated 03 29, 19 5:28:16 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * ShCurriculumSem generated by hbm2java
 */
@Entity
@Table(name="sh_curriculum_sem"
    ,catalog="seniorhighdb"
)
public class ShCurriculumSem  implements java.io.Serializable {


     private String currSemId;
     private boolean currSem;
     private Byte currYrlevel;
     private ShCurriculumHdr shCurriculumHdr;

    public ShCurriculumSem() {
    }

	
    public ShCurriculumSem(String currSemId, boolean currSem, ShCurriculumHdr shCurriculumHdr) {
        this.currSemId = currSemId;
        this.currSem = currSem;
        this.shCurriculumHdr = shCurriculumHdr;
    }
    public ShCurriculumSem(String currSemId, boolean currSem, Byte currYrlevel, ShCurriculumHdr shCurriculumHdr) {
       this.currSemId = currSemId;
       this.currSem = currSem;
       this.currYrlevel = currYrlevel;
       this.shCurriculumHdr = shCurriculumHdr;
    }
   
     @Id 

    
    @Column(name="curr_sem_id", unique=true, nullable=false, length=10)
    public String getCurrSemId() {
        return this.currSemId;
    }
    
    public void setCurrSemId(String currSemId) {
        this.currSemId = currSemId;
    }

    
    @Column(name="curr_sem", nullable=false)
    public boolean isCurrSem() {
        return this.currSem;
    }
    
    public void setCurrSem(boolean currSem) {
        this.currSem = currSem;
    }

    
    @Column(name="curr_yrlevel")
    public Byte getCurrYrlevel() {
        return this.currYrlevel;
    }
    
    public void setCurrYrlevel(Byte currYrlevel) {
        this.currYrlevel = currYrlevel;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="curr_hdr_id", nullable=false)
    public ShCurriculumHdr getShCurriculumHdr() {
        return this.shCurriculumHdr;
    }
    
    public void setShCurriculumHdr(ShCurriculumHdr shCurriculumHdr) {
        this.shCurriculumHdr = shCurriculumHdr;
    }




}


