package entity;
// Generated 03 29, 19 5:28:16 PM by Hibernate Tools 4.3.1


import java.awt.Checkbox;
import java.util.Date;
import javafx.beans.property.BooleanProperty;
import javafx.scene.control.CheckBox;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Transient;

/**
 * ShCurrDtl generated by hbm2java
 */
@Entity
@Table(name="sh_curr_dtl"
    ,catalog="seniorhighdb"
)
public class ShCurrDtl  implements java.io.Serializable {


@Id
    @GeneratedValue(strategy=IDENTITY)
    @Column(name="curr_dtl_id", unique=true, nullable=false, length=20)
     private Integer currDtlId;
     @Temporal(TemporalType.TIMESTAMP)
     @Column(name="date_created", length=19)
     private Date dateCreated;
     @Column(name="sem")
     private Integer sem;
     @ManyToOne(fetch=FetchType.LAZY)
     @JoinColumn(name="f_course")
     private ShCourseList shCourseList;
     @ManyToOne(fetch=FetchType.LAZY)
     @JoinColumn(name="f_curr_hdr")
     private ShCurrHdr shCurrHdr;
     @Temporal(TemporalType.TIMESTAMP)
     @Column(name="ts", insertable=false, updatable=false, length=19)
     private Date ts;
     @Column(name="yrlevel")
     private Integer yrlevel;
     
     @Transient
     private String customSy;   
     
     @Transient
     private String customFCurrSy;  
     
     @Transient
     private CheckBox customSelect;    
  

    public ShCurrDtl() {
         this.customSelect = new CheckBox();   
    }

	
    public ShCurrDtl(Date ts) {
        this.ts = ts;
        this.customSelect = new CheckBox();   
    }
    public ShCurrDtl(Date dateCreated, Integer sem, ShCourseList shCourseList, ShCurrHdr shCurrHdr, Date ts, Integer yrlevel) {
       this.dateCreated = dateCreated;
       this.sem = sem;
       this.shCourseList = shCourseList;
       this.shCurrHdr = shCurrHdr;
       this.ts = ts;
       this.yrlevel = yrlevel;
       this.customSelect = new CheckBox();   
    }
   
    public Integer getCurrDtlId() {
        return this.currDtlId;
    }
    
    public void setCurrDtlId(Integer currDtlId) {
        this.currDtlId = currDtlId;
    }

    public Date getDateCreated() {
        return this.dateCreated;
    }
    
    public void setDateCreated(Date dateCreated) {
        this.dateCreated = dateCreated;
    }

    
    public Integer getSem() {
        return this.sem;
    }
    
    public void setSem(Integer sem) {
        this.sem = sem;
    }

    public ShCourseList getShCourseList() {
        return this.shCourseList;
    }
    
    public void setShCourseList(ShCourseList shCourseList) {
        this.shCourseList = shCourseList;
    }

    public ShCurrHdr getShCurrHdr() {
        return this.shCurrHdr;
    }
    
    public void setShCurrHdr(ShCurrHdr shCurrHdr) {
        this.shCurrHdr = shCurrHdr;
    }

    public Date getTs() {
        return this.ts;
    }
    
    public void setTs(Date ts) {
        this.ts = ts;
    }

    
    public Integer getYrlevel() {
        return this.yrlevel;
    }
    
    public void setYrlevel(Integer yrlevel) {
        this.yrlevel = yrlevel;
    }

    public String getCustomSy() {
        return customSy;
    }

    public void setCustomSy(String customSy) {
        this.customSy = customSy;
    }


    public CheckBox getCustomSelect() {
        return customSelect;
    }
 
    public void setCustomSelect(CheckBox customSelect) {
        this.customSelect = customSelect;
    }

    public String getCustomFCurrSy() {
        return customFCurrSy;
    }

    public void setCustomFCurrSy(String customFCurrSy) {
        this.customFCurrSy = customFCurrSy;
    }

   




}


