package entity;
// Generated 03 29, 19 5:28:16 PM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * ShCurrSy generated by hbm2java
 */
@Entity
@Table(name="sh_curr_sy"
    ,catalog="seniorhighdb"
)
public class ShCurrSy  implements java.io.Serializable {


     private Integer currSyId;
     private Date dateCreated;
     private ShCurrHdr shCurrHdr;
     private String sy;
     private Date ts;

    public ShCurrSy() {
    }

	
    public ShCurrSy(Date ts) {
        this.ts = ts;
    }
    public ShCurrSy(Date dateCreated, ShCurrHdr shCurrHdr, String sy, Date ts) {
       this.dateCreated = dateCreated;
       this.shCurrHdr = shCurrHdr;
       this.sy = sy;
       this.ts = ts;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="curr_sy_id", unique=true, nullable=false)
    public Integer getCurrSyId() {
        return this.currSyId;
    }
    
    public void setCurrSyId(Integer currSyId) {
        this.currSyId = currSyId;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="date_created", length=19)
    public Date getDateCreated() {
        return this.dateCreated;
    }
    
    public void setDateCreated(Date dateCreated) {
        this.dateCreated = dateCreated;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="f_curr_hdr")
    public ShCurrHdr getShCurrHdr() {
        return this.shCurrHdr;
    }
    
    public void setShCurrHdr(ShCurrHdr shCurrHdr) {
        this.shCurrHdr = shCurrHdr;
    }

    
    @Column(name="sy", length=10)
    public String getSy() {
        return this.sy;
    }
    
    public void setSy(String sy) {
        this.sy = sy;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="ts", insertable=false, updatable=false, length=19)
    public Date getTs() {
        return this.ts;
    }
    
    public void setTs(Date ts) {
        this.ts = ts;
    }




}


