package entity;
// Generated 03 29, 19 5:28:16 PM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * ShDates generated by hbm2java
 */
@Entity
@Table(name="sh_dates"
    ,catalog="seniorhighdb"
)
public class ShDates  implements java.io.Serializable {


     private Integer id;
     private Date enrollDate;
     private Date graduationDate;
     private Integer sem;
     private String sy;
     private Date ts;

    public ShDates() {
    }

	
    public ShDates(Date ts) {
        this.ts = ts;
    }
    public ShDates(Date enrollDate, Date graduationDate, Integer sem, String sy, Date ts) {
       this.enrollDate = enrollDate;
       this.graduationDate = graduationDate;
       this.sem = sem;
       this.sy = sy;
       this.ts = ts;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="enroll_date", length=10)
    public Date getEnrollDate() {
        return this.enrollDate;
    }
    
    public void setEnrollDate(Date enrollDate) {
        this.enrollDate = enrollDate;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="graduation_date", length=10)
    public Date getGraduationDate() {
        return this.graduationDate;
    }
    
    public void setGraduationDate(Date graduationDate) {
        this.graduationDate = graduationDate;
    }

    
    @Column(name="sem")
    public Integer getSem() {
        return this.sem;
    }
    
    public void setSem(Integer sem) {
        this.sem = sem;
    }

    
    @Column(name="sy", length=10)
    public String getSy() {
        return this.sy;
    }
    
    public void setSy(String sy) {
        this.sy = sy;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="ts", nullable=false, length=19)
    public Date getTs() {
        return this.ts;
    }
    
    public void setTs(Date ts) {
        this.ts = ts;
    }




}


