package entity;
// Generated 06 1, 19 5:52:32 AM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * ShDaysId generated by hbm2java
 */
@Embeddable
public class ShDaysId  implements java.io.Serializable {


     private int daysId;
     private String days;

    public ShDaysId() {
    }

    public ShDaysId(int daysId, String days) {
       this.daysId = daysId;
       this.days = days;
    }
   


    @Column(name="days_id", nullable=false)
    public int getDaysId() {
        return this.daysId;
    }
    
    public void setDaysId(int daysId) {
        this.daysId = daysId;
    }


    @Column(name="days", nullable=false, length=10)
    public String getDays() {
        return this.days;
    }
    
    public void setDays(String days) {
        this.days = days;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof ShDaysId) ) return false;
		 ShDaysId castOther = ( ShDaysId ) other; 
         
		 return (this.getDaysId()==castOther.getDaysId())
 && ( (this.getDays()==castOther.getDays()) || ( this.getDays()!=null && castOther.getDays()!=null && this.getDays().equals(castOther.getDays()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getDaysId();
         result = 37 * result + ( getDays() == null ? 0 : this.getDays().hashCode() );
         return result;
   }   


}


