package entity;
// Generated 03 29, 19 5:28:16 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * ShFee2 generated by hbm2java
 */
@Entity
@Table(name="sh_fee2"
    ,catalog="seniorhighdb"
)
public class ShFee2  implements java.io.Serializable {


     private Integer feeid;
     private Date CTs;
     private String code;
     private BigDecimal fee;
     private Integer gradelevel;
     private String itemname;
     private String saCode;
     private Integer sem;
     private String strandCode;
     private String strandcode;
     private String term;
     private Boolean tobedeleted;
     private BigDecimal units;
     private Integer withLab;

    public ShFee2() {
    }

	
    public ShFee2(Date CTs, String code, BigDecimal fee, String term) {
        this.CTs = CTs;
        this.code = code;
        this.fee = fee;
        this.term = term;
    }
    public ShFee2(Date CTs, String code, BigDecimal fee, Integer gradelevel, String itemname, String saCode, Integer sem, String strandCode, String strandcode, String term, Boolean tobedeleted, BigDecimal units, Integer withLab) {
       this.CTs = CTs;
       this.code = code;
       this.fee = fee;
       this.gradelevel = gradelevel;
       this.itemname = itemname;
       this.saCode = saCode;
       this.sem = sem;
       this.strandCode = strandCode;
       this.strandcode = strandcode;
       this.term = term;
       this.tobedeleted = tobedeleted;
       this.units = units;
       this.withLab = withLab;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="feeid", unique=true, nullable=false)
    public Integer getFeeid() {
        return this.feeid;
    }
    
    public void setFeeid(Integer feeid) {
        this.feeid = feeid;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="c_ts", nullable=false, length=19)
    public Date getCTs() {
        return this.CTs;
    }
    
    public void setCTs(Date CTs) {
        this.CTs = CTs;
    }

    
    @Column(name="code", nullable=false, length=50)
    public String getCode() {
        return this.code;
    }
    
    public void setCode(String code) {
        this.code = code;
    }

    
    @Column(name="fee", nullable=false, precision=10, scale=0)
    public BigDecimal getFee() {
        return this.fee;
    }
    
    public void setFee(BigDecimal fee) {
        this.fee = fee;
    }

    
    @Column(name="gradelevel")
    public Integer getGradelevel() {
        return this.gradelevel;
    }
    
    public void setGradelevel(Integer gradelevel) {
        this.gradelevel = gradelevel;
    }

    
    @Column(name="itemname", length=150)
    public String getItemname() {
        return this.itemname;
    }
    
    public void setItemname(String itemname) {
        this.itemname = itemname;
    }

    
    @Column(name="sa_code", length=50)
    public String getSaCode() {
        return this.saCode;
    }
    
    public void setSaCode(String saCode) {
        this.saCode = saCode;
    }

    
    @Column(name="sem")
    public Integer getSem() {
        return this.sem;
    }
    
    public void setSem(Integer sem) {
        this.sem = sem;
    }

    
    @Column(name="strand_code", length=10)
    public String getStrandCode() {
        return this.strandCode;
    }
    
    public void setStrandCode(String strandCode) {
        this.strandCode = strandCode;
    }

    
    @Column(name="strandcode", length=100)
    public String getStrandcode() {
        return this.strandcode;
    }
    
    public void setStrandcode(String strandcode) {
        this.strandcode = strandcode;
    }

    
    @Column(name="term", nullable=false, length=11)
    public String getTerm() {
        return this.term;
    }
    
    public void setTerm(String term) {
        this.term = term;
    }

    
    @Column(name="tobedeleted")
    public Boolean getTobedeleted() {
        return this.tobedeleted;
    }
    
    public void setTobedeleted(Boolean tobedeleted) {
        this.tobedeleted = tobedeleted;
    }

    
    @Column(name="units", precision=4, scale=1)
    public BigDecimal getUnits() {
        return this.units;
    }
    
    public void setUnits(BigDecimal units) {
        this.units = units;
    }

    
    @Column(name="with_lab")
    public Integer getWithLab() {
        return this.withLab;
    }
    
    public void setWithLab(Integer withLab) {
        this.withLab = withLab;
    }




}


