package entity;
// Generated 03 29, 19 5:28:16 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * ShQuarters generated by hbm2java
 */
@Entity
@Table(name="sh_quarters"
    ,catalog="seniorhighdb"
)
public class ShQuarters  implements java.io.Serializable {


     private String quarter;
     private Boolean quarterIsactive;
     private String quarterName;

    public ShQuarters() {
    }

	
    public ShQuarters(String quarter) {
        this.quarter = quarter;
    }
    public ShQuarters(String quarter, Boolean quarterIsactive, String quarterName) {
       this.quarter = quarter;
       this.quarterIsactive = quarterIsactive;
       this.quarterName = quarterName;
    }
   
     @Id 

    
    @Column(name="quarter", unique=true, nullable=false, length=1)
    public String getQuarter() {
        return this.quarter;
    }
    
    public void setQuarter(String quarter) {
        this.quarter = quarter;
    }

    
    @Column(name="quarter_isactive")
    public Boolean getQuarterIsactive() {
        return this.quarterIsactive;
    }
    
    public void setQuarterIsactive(Boolean quarterIsactive) {
        this.quarterIsactive = quarterIsactive;
    }

    
    @Column(name="quarter_name", length=15)
    public String getQuarterName() {
        return this.quarterName;
    }
    
    public void setQuarterName(String quarterName) {
        this.quarterName = quarterName;
    }




}


