package entity;
// Generated 03 29, 19 5:28:16 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * ShRankingFinal generated by hbm2java
 */
@Entity
@Table(name="sh_ranking_final"
    ,catalog="seniorhighdb"
)
public class ShRankingFinal  implements java.io.Serializable {


     private Integer rdtlId;
     private Integer FRhdr;
     private BigDecimal gpa1;
     private BigDecimal gpa2;
     private BigDecimal gpaFinal;
     private String studIdnum;
     private String sy;
     private Date ts;
     private Integer yrLevel;

    public ShRankingFinal() {
    }

	
    public ShRankingFinal(Date ts) {
        this.ts = ts;
    }
    public ShRankingFinal(Integer FRhdr, BigDecimal gpa1, BigDecimal gpa2, BigDecimal gpaFinal, String studIdnum, String sy, Date ts, Integer yrLevel) {
       this.FRhdr = FRhdr;
       this.gpa1 = gpa1;
       this.gpa2 = gpa2;
       this.gpaFinal = gpaFinal;
       this.studIdnum = studIdnum;
       this.sy = sy;
       this.ts = ts;
       this.yrLevel = yrLevel;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="rdtl_id", unique=true, nullable=false)
    public Integer getRdtlId() {
        return this.rdtlId;
    }
    
    public void setRdtlId(Integer rdtlId) {
        this.rdtlId = rdtlId;
    }

    
    @Column(name="f_rhdr")
    public Integer getFRhdr() {
        return this.FRhdr;
    }
    
    public void setFRhdr(Integer FRhdr) {
        this.FRhdr = FRhdr;
    }

    
    @Column(name="gpa1", precision=6, scale=0)
    public BigDecimal getGpa1() {
        return this.gpa1;
    }
    
    public void setGpa1(BigDecimal gpa1) {
        this.gpa1 = gpa1;
    }

    
    @Column(name="gpa2", precision=6, scale=0)
    public BigDecimal getGpa2() {
        return this.gpa2;
    }
    
    public void setGpa2(BigDecimal gpa2) {
        this.gpa2 = gpa2;
    }

    
    @Column(name="gpa_final", precision=6, scale=0)
    public BigDecimal getGpaFinal() {
        return this.gpaFinal;
    }
    
    public void setGpaFinal(BigDecimal gpaFinal) {
        this.gpaFinal = gpaFinal;
    }

    
    @Column(name="stud_idnum", length=15)
    public String getStudIdnum() {
        return this.studIdnum;
    }
    
    public void setStudIdnum(String studIdnum) {
        this.studIdnum = studIdnum;
    }

    
    @Column(name="sy", length=10)
    public String getSy() {
        return this.sy;
    }
    
    public void setSy(String sy) {
        this.sy = sy;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="ts", nullable=false, length=19)
    public Date getTs() {
        return this.ts;
    }
    
    public void setTs(Date ts) {
        this.ts = ts;
    }

    
    @Column(name="yr_level")
    public Integer getYrLevel() {
        return this.yrLevel;
    }
    
    public void setYrLevel(Integer yrLevel) {
        this.yrLevel = yrLevel;
    }




}


