package entity;
// Generated 03 29, 19 5:28:16 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * ShRankingDtl generated by hbm2java
 */
@Entity
@Table(name="sh_ranking_dtl"
    ,catalog="seniorhighdb"
)
public class ShRankingDtl  implements java.io.Serializable {


     private Integer rdtlId;
     private Integer FRhdr;
     private BigDecimal gpa;
     private Integer isQualified;
     private Integer sem;
     private String studIdnum;
     private String sy;
     private Date ts;
     private Integer yrLevel;

    public ShRankingDtl() {
    }

	
    public ShRankingDtl(Date ts) {
        this.ts = ts;
    }
    public ShRankingDtl(Integer FRhdr, BigDecimal gpa, Integer isQualified, Integer sem, String studIdnum, String sy, Date ts, Integer yrLevel) {
       this.FRhdr = FRhdr;
       this.gpa = gpa;
       this.isQualified = isQualified;
       this.sem = sem;
       this.studIdnum = studIdnum;
       this.sy = sy;
       this.ts = ts;
       this.yrLevel = yrLevel;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="rdtl_id", unique=true, nullable=false)
    public Integer getRdtlId() {
        return this.rdtlId;
    }
    
    public void setRdtlId(Integer rdtlId) {
        this.rdtlId = rdtlId;
    }

    
    @Column(name="f_rhdr")
    public Integer getFRhdr() {
        return this.FRhdr;
    }
    
    public void setFRhdr(Integer FRhdr) {
        this.FRhdr = FRhdr;
    }

    
    @Column(name="gpa", precision=6, scale=0)
    public BigDecimal getGpa() {
        return this.gpa;
    }
    
    public void setGpa(BigDecimal gpa) {
        this.gpa = gpa;
    }

    
    @Column(name="is_qualified")
    public Integer getIsQualified() {
        return this.isQualified;
    }
    
    public void setIsQualified(Integer isQualified) {
        this.isQualified = isQualified;
    }

    
    @Column(name="sem")
    public Integer getSem() {
        return this.sem;
    }
    
    public void setSem(Integer sem) {
        this.sem = sem;
    }

    
    @Column(name="stud_idnum", length=15)
    public String getStudIdnum() {
        return this.studIdnum;
    }
    
    public void setStudIdnum(String studIdnum) {
        this.studIdnum = studIdnum;
    }

    
    @Column(name="sy", length=10)
    public String getSy() {
        return this.sy;
    }
    
    public void setSy(String sy) {
        this.sy = sy;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="ts", nullable=false, length=19)
    public Date getTs() {
        return this.ts;
    }
    
    public void setTs(Date ts) {
        this.ts = ts;
    }

    
    @Column(name="yr_level")
    public Integer getYrLevel() {
        return this.yrLevel;
    }
    
    public void setYrLevel(Integer yrLevel) {
        this.yrLevel = yrLevel;
    }




}


