package entity;
// Generated 03 29, 19 5:28:16 PM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * ShRankingHdr generated by hbm2java
 */
@Entity
@Table(name="sh_ranking_hdr"
    ,catalog="seniorhighdb"
)
public class ShRankingHdr  implements java.io.Serializable {


     private Integer rhdrId;
     private Integer sem;
     private String sy;
     private Date ts;
     private Integer yrLevel;

    public ShRankingHdr() {
    }

	
    public ShRankingHdr(Date ts) {
        this.ts = ts;
    }
    public ShRankingHdr(Integer sem, String sy, Date ts, Integer yrLevel) {
       this.sem = sem;
       this.sy = sy;
       this.ts = ts;
       this.yrLevel = yrLevel;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="rhdr_id", unique=true, nullable=false)
    public Integer getRhdrId() {
        return this.rhdrId;
    }
    
    public void setRhdrId(Integer rhdrId) {
        this.rhdrId = rhdrId;
    }

    
    @Column(name="sem")
    public Integer getSem() {
        return this.sem;
    }
    
    public void setSem(Integer sem) {
        this.sem = sem;
    }

    
    @Column(name="sy", length=10)
    public String getSy() {
        return this.sy;
    }
    
    public void setSy(String sy) {
        this.sy = sy;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="ts", nullable=false, length=19)
    public Date getTs() {
        return this.ts;
    }
    
    public void setTs(Date ts) {
        this.ts = ts;
    }

    
    @Column(name="yr_level")
    public Integer getYrLevel() {
        return this.yrLevel;
    }
    
    public void setYrLevel(Integer yrLevel) {
        this.yrLevel = yrLevel;
    }




}


