package entity;
// Generated 03 29, 19 5:28:16 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * ShSections generated by hbm2java
 */
@Entity
@Table(name="sh_sections"
    ,catalog="seniorhighdb"
)
public class ShSections  implements java.io.Serializable {


     private String section;

    public ShSections() {
    }

    public ShSections(String section) {
       this.section = section;
    }
   
     @Id 

    
    @Column(name="section", unique=true, nullable=false, length=3)
    public String getSection() {
        return this.section;
    }
    
    public void setSection(String section) {
        this.section = section;
    }




}


