package entity;
// Generated 03 29, 19 5:28:16 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * ShStudlistId generated by hbm2java
 */
@Embeddable
public class ShStudlistId  implements java.io.Serializable {


     private int sem;
     private String studIdnum;
     private String sy;

    public ShStudlistId() {
    }

    public ShStudlistId(int sem, String studIdnum, String sy) {
       this.sem = sem;
       this.studIdnum = studIdnum;
       this.sy = sy;
    }
   


    @Column(name="sem", nullable=false)
    public int getSem() {
        return this.sem;
    }
    
    public void setSem(int sem) {
        this.sem = sem;
    }


    @Column(name="stud_idnum", nullable=false, length=6)
    public String getStudIdnum() {
        return this.studIdnum;
    }
    
    public void setStudIdnum(String studIdnum) {
        this.studIdnum = studIdnum;
    }


    @Column(name="sy", nullable=false, length=9)
    public String getSy() {
        return this.sy;
    }
    
    public void setSy(String sy) {
        this.sy = sy;
    }




}


