package entity;
// Generated 03 29, 19 5:28:16 PM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * ShStudlist generated by hbm2java
 */
@Entity
@Table(name="sh_studlist"
    ,catalog="seniorhighdb"
)
public class ShStudlist  implements java.io.Serializable {


     private ShStudlistId id;
     private String appNo;
     private Integer confirm;
     private Date datePaid;
     private Integer enrolStatus;
     private Integer isAssess;
     private Boolean isCardprinted;
     private Date lastUpdated;
     private Integer regConfirm;
     private Integer status;
     private Integer statusIn;
     private Integer statusOut;
     private String studFname;
     private String studLname;
     private String studMi;
     private String studSuffix;
     private Date transdate;

    public ShStudlist() {
    }

	
    public ShStudlist(ShStudlistId id, Date transdate) {
        this.id = id;
        this.transdate = transdate;
    }
    public ShStudlist(ShStudlistId id, String appNo, Integer confirm, Date datePaid, Integer enrolStatus, Integer isAssess, Boolean isCardprinted, Date lastUpdated, Integer regConfirm, Integer status, Integer statusIn, Integer statusOut, String studFname, String studLname, String studMi, String studSuffix, Date transdate) {
       this.id = id;
       this.appNo = appNo;
       this.confirm = confirm;
       this.datePaid = datePaid;
       this.enrolStatus = enrolStatus;
       this.isAssess = isAssess;
       this.isCardprinted = isCardprinted;
       this.lastUpdated = lastUpdated;
       this.regConfirm = regConfirm;
       this.status = status;
       this.statusIn = statusIn;
       this.statusOut = statusOut;
       this.studFname = studFname;
       this.studLname = studLname;
       this.studMi = studMi;
       this.studSuffix = studSuffix;
       this.transdate = transdate;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="sem", column=@Column(name="sem", nullable=false) ), 
        @AttributeOverride(name="studIdnum", column=@Column(name="stud_idnum", nullable=false, length=6) ), 
        @AttributeOverride(name="sy", column=@Column(name="sy", nullable=false, length=9) ) } )
    public ShStudlistId getId() {
        return this.id;
    }
    
    public void setId(ShStudlistId id) {
        this.id = id;
    }

    
    @Column(name="app_no", length=10)
    public String getAppNo() {
        return this.appNo;
    }
    
    public void setAppNo(String appNo) {
        this.appNo = appNo;
    }

    
    @Column(name="confirm")
    public Integer getConfirm() {
        return this.confirm;
    }
    
    public void setConfirm(Integer confirm) {
        this.confirm = confirm;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="date_paid", length=10)
    public Date getDatePaid() {
        return this.datePaid;
    }
    
    public void setDatePaid(Date datePaid) {
        this.datePaid = datePaid;
    }

    
    @Column(name="enrol_status")
    public Integer getEnrolStatus() {
        return this.enrolStatus;
    }
    
    public void setEnrolStatus(Integer enrolStatus) {
        this.enrolStatus = enrolStatus;
    }

    
    @Column(name="is_assess")
    public Integer getIsAssess() {
        return this.isAssess;
    }
    
    public void setIsAssess(Integer isAssess) {
        this.isAssess = isAssess;
    }

    
    @Column(name="is_cardprinted")
    public Boolean getIsCardprinted() {
        return this.isCardprinted;
    }
    
    public void setIsCardprinted(Boolean isCardprinted) {
        this.isCardprinted = isCardprinted;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="last_updated", insertable=false, length=19)
    public Date getLastUpdated() {
        return this.lastUpdated;
    }
    
    public void setLastUpdated(Date lastUpdated) {
        this.lastUpdated = lastUpdated;
    }

    
    @Column(name="reg_confirm")
    public Integer getRegConfirm() {
        return this.regConfirm;
    }
    
    public void setRegConfirm(Integer regConfirm) {
        this.regConfirm = regConfirm;
    }

    
    @Column(name="status")
    public Integer getStatus() {
        return this.status;
    }
    
    public void setStatus(Integer status) {
        this.status = status;
    }

    
    @Column(name="status_in")
    public Integer getStatusIn() {
        return this.statusIn;
    }
    
    public void setStatusIn(Integer statusIn) {
        this.statusIn = statusIn;
    }

    
    @Column(name="status_out")
    public Integer getStatusOut() {
        return this.statusOut;
    }
    
    public void setStatusOut(Integer statusOut) {
        this.statusOut = statusOut;
    }

    
    @Column(name="stud_fname", length=40)
    public String getStudFname() {
        return this.studFname;
    }
    
    public void setStudFname(String studFname) {
        this.studFname = studFname;
    }

    
    @Column(name="stud_lname", length=40)
    public String getStudLname() {
        return this.studLname;
    }
    
    public void setStudLname(String studLname) {
        this.studLname = studLname;
    }

    
    @Column(name="stud_mi", length=4)
    public String getStudMi() {
        return this.studMi;
    }
    
    public void setStudMi(String studMi) {
        this.studMi = studMi;
    }

    
    @Column(name="stud_suffix", length=10)
    public String getStudSuffix() {
        return this.studSuffix;
    }
    
    public void setStudSuffix(String studSuffix) {
        this.studSuffix = studSuffix;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="transdate", insertable=false, length=19)
    public Date getTransdate() {
        return this.transdate;
    }
    
    public void setTransdate(Date transdate) {
        this.transdate = transdate;
    }




}


