package entity;
// Generated 03 29, 19 5:28:16 PM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * ShStudStrand generated by hbm2java
 */
@Entity
@Table(name="sh_stud_strand"
    ,catalog="seniorhighdb"
)
public class ShStudStrand  implements java.io.Serializable {


     private String ssId;
     private Date created;
     private Double gpa;
     private Date lastUpdate;
     private Byte ssIsreg;
     private Integer ssSem;
     private String ssStatus;
     private String ssSy;
     private Integer ssYrLevel;
     private String strandCode;
     private String strandGroup;
     private Integer strandSpecial;
     private String strandSpecialdesc;
     private String studIdnum;
     private Integer totSubjWithgrade;

    public ShStudStrand() {
    }

	
    public ShStudStrand(String ssId, Date lastUpdate, String strandCode, String studIdnum) {
        this.ssId = ssId;
        this.lastUpdate = lastUpdate;
        this.strandCode = strandCode;
        this.studIdnum = studIdnum;
    }
    public ShStudStrand(String ssId, Date created, Double gpa, Date lastUpdate, Byte ssIsreg, Integer ssSem, String ssStatus, String ssSy, Integer ssYrLevel, String strandCode, String strandGroup, Integer strandSpecial, String strandSpecialdesc, String studIdnum, Integer totSubjWithgrade) {
       this.ssId = ssId;
       this.created = created;
       this.gpa = gpa;
       this.lastUpdate = lastUpdate;
       this.ssIsreg = ssIsreg;
       this.ssSem = ssSem;
       this.ssStatus = ssStatus;
       this.ssSy = ssSy;
       this.ssYrLevel = ssYrLevel;
       this.strandCode = strandCode;
       this.strandGroup = strandGroup;
       this.strandSpecial = strandSpecial;
       this.strandSpecialdesc = strandSpecialdesc;
       this.studIdnum = studIdnum;
       this.totSubjWithgrade = totSubjWithgrade;
    }
   
     @Id 

    
    @Column(name="ss_id", unique=true, nullable=false, length=20)
    public String getSsId() {
        return this.ssId;
    }
    
    public void setSsId(String ssId) {
        this.ssId = ssId;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="created", insertable=false, length=19)
    public Date getCreated() {
        return this.created;
    }
    
    public void setCreated(Date created) {
        this.created = created;
    }

    
    @Column(name="gpa", precision=10, scale=0)
    public Double getGpa() {
        return this.gpa;
    }
    
    public void setGpa(Double gpa) {
        this.gpa = gpa;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="last_update", nullable=false, insertable=false, length=19)
    public Date getLastUpdate() {
        return this.lastUpdate;
    }
    
    public void setLastUpdate(Date lastUpdate) {
        this.lastUpdate = lastUpdate;
    }

    
    @Column(name="ss_isreg")
    public Byte getSsIsreg() {
        return this.ssIsreg;
    }
    
    public void setSsIsreg(Byte ssIsreg) {
        this.ssIsreg = ssIsreg;
    }

    
    @Column(name="ss_sem")
    public Integer getSsSem() {
        return this.ssSem;
    }
    
    public void setSsSem(Integer ssSem) {
        this.ssSem = ssSem;
    }

    
    @Column(name="ss_status", length=20)
    public String getSsStatus() {
        return this.ssStatus;
    }
    
    public void setSsStatus(String ssStatus) {
        this.ssStatus = ssStatus;
    }

    
    @Column(name="ss_sy", length=9)
    public String getSsSy() {
        return this.ssSy;
    }
    
    public void setSsSy(String ssSy) {
        this.ssSy = ssSy;
    }

    
    @Column(name="ss_yr_level")
    public Integer getSsYrLevel() {
        return this.ssYrLevel;
    }
    
    public void setSsYrLevel(Integer ssYrLevel) {
        this.ssYrLevel = ssYrLevel;
    }

    
    @Column(name="strand_code", nullable=false, length=20)
    public String getStrandCode() {
        return this.strandCode;
    }
    
    public void setStrandCode(String strandCode) {
        this.strandCode = strandCode;
    }

    
    @Column(name="strand_group", length=3)
    public String getStrandGroup() {
        return this.strandGroup;
    }
    
    public void setStrandGroup(String strandGroup) {
        this.strandGroup = strandGroup;
    }

    
    @Column(name="strand_special")
    public Integer getStrandSpecial() {
        return this.strandSpecial;
    }
    
    public void setStrandSpecial(Integer strandSpecial) {
        this.strandSpecial = strandSpecial;
    }

    
    @Column(name="strand_specialdesc", length=30)
    public String getStrandSpecialdesc() {
        return this.strandSpecialdesc;
    }
    
    public void setStrandSpecialdesc(String strandSpecialdesc) {
        this.strandSpecialdesc = strandSpecialdesc;
    }

    
    @Column(name="stud_idnum", nullable=false, length=10)
    public String getStudIdnum() {
        return this.studIdnum;
    }
    
    public void setStudIdnum(String studIdnum) {
        this.studIdnum = studIdnum;
    }

    
    @Column(name="tot_subj_withgrade")
    public Integer getTotSubjWithgrade() {
        return this.totSubjWithgrade;
    }
    
    public void setTotSubjWithgrade(Integer totSubjWithgrade) {
        this.totSubjWithgrade = totSubjWithgrade;
    }




}


