package entity;
// Generated 03 29, 19 5:28:16 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * ShTimes generated by hbm2java
 */
@Entity
@Table(name="sh_times"
    ,catalog="seniorhighdb"
)
public class ShTimes  implements java.io.Serializable {


     private String times;
     private String amPm;
     private int timecode;
     private String timesdesc;

    public ShTimes() {
    }

	
    public ShTimes(String times, int timecode) {
        this.times = times;
        this.timecode = timecode;
    }
    public ShTimes(String times, String amPm, int timecode, String timesdesc) {
       this.times = times;
       this.amPm = amPm;
       this.timecode = timecode;
       this.timesdesc = timesdesc;
    }
   
     @Id 

    
    @Column(name="times", unique=true, nullable=false, length=10)
    public String getTimes() {
        return this.times;
    }
    
    public void setTimes(String times) {
        this.times = times;
    }

    
    @Column(name="am_pm", length=10)
    public String getAmPm() {
        return this.amPm;
    }
    
    public void setAmPm(String amPm) {
        this.amPm = amPm;
    }

    
    @Column(name="timecode", nullable=false)
    public int getTimecode() {
        return this.timecode;
    }
    
    public void setTimecode(int timecode) {
        this.timecode = timecode;
    }

    
    @Column(name="timesdesc", length=10)
    public String getTimesdesc() {
        return this.timesdesc;
    }
    
    public void setTimesdesc(String timesdesc) {
        this.timesdesc = timesdesc;
    }




}


