package entity;
// Generated 03 29, 19 5:28:16 PM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * ShTmplog generated by hbm2java
 */
@Entity
@Table(name="sh_tmplog"
    ,catalog="seniorhighdb"
)
public class ShTmplog  implements java.io.Serializable {


     private String idnum;
     private Date ts;

    public ShTmplog() {
    }

	
    public ShTmplog(String idnum) {
        this.idnum = idnum;
    }
    public ShTmplog(String idnum, Date ts) {
       this.idnum = idnum;
       this.ts = ts;
    }
   
     @Id 

    
    @Column(name="idnum", unique=true, nullable=false, length=6)
    public String getIdnum() {
        return this.idnum;
    }
    
    public void setIdnum(String idnum) {
        this.idnum = idnum;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="ts", length=19)
    public Date getTs() {
        return this.ts;
    }
    
    public void setTs(Date ts) {
        this.ts = ts;
    }




}


