package entity;
// Generated 03 29, 19 5:28:16 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * ShWebTmpaccount generated by hbm2java
 */
@Entity
@Table(name="sh_web_tmpaccount"
    ,catalog="seniorhighdb"
)
public class ShWebTmpaccount  implements java.io.Serializable {


     private String accntid;
     private String idnum;
     private String itemcode;
     private BigDecimal itemfee;
     private String itemname;
     private Byte pmode;
     private Date ts;

    public ShWebTmpaccount() {
    }

	
    public ShWebTmpaccount(String accntid, String idnum) {
        this.accntid = accntid;
        this.idnum = idnum;
    }
    public ShWebTmpaccount(String accntid, String idnum, String itemcode, BigDecimal itemfee, String itemname, Byte pmode, Date ts) {
       this.accntid = accntid;
       this.idnum = idnum;
       this.itemcode = itemcode;
       this.itemfee = itemfee;
       this.itemname = itemname;
       this.pmode = pmode;
       this.ts = ts;
    }
   
     @Id 

    
    @Column(name="accntid", unique=true, nullable=false, length=10)
    public String getAccntid() {
        return this.accntid;
    }
    
    public void setAccntid(String accntid) {
        this.accntid = accntid;
    }

    
    @Column(name="idnum", nullable=false, length=6)
    public String getIdnum() {
        return this.idnum;
    }
    
    public void setIdnum(String idnum) {
        this.idnum = idnum;
    }

    
    @Column(name="itemcode", length=20)
    public String getItemcode() {
        return this.itemcode;
    }
    
    public void setItemcode(String itemcode) {
        this.itemcode = itemcode;
    }

    
    @Column(name="itemfee", precision=10, scale=0)
    public BigDecimal getItemfee() {
        return this.itemfee;
    }
    
    public void setItemfee(BigDecimal itemfee) {
        this.itemfee = itemfee;
    }

    
    @Column(name="itemname", length=50)
    public String getItemname() {
        return this.itemname;
    }
    
    public void setItemname(String itemname) {
        this.itemname = itemname;
    }

    
    @Column(name="pmode")
    public Byte getPmode() {
        return this.pmode;
    }
    
    public void setPmode(Byte pmode) {
        this.pmode = pmode;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="ts", length=19)
    public Date getTs() {
        return this.ts;
    }
    
    public void setTs(Date ts) {
        this.ts = ts;
    }




}


