package entity;
// Generated 03 29, 19 5:28:16 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Year generated by hbm2java
 */
@Entity
@Table(name="year"
    ,catalog="seniorhighdb"
)
public class Year  implements java.io.Serializable {


     private boolean year;

    public Year() {
    }

    public Year(boolean year) {
       this.year = year;
    }
   
     @Id 

    
    @Column(name="year", unique=true, nullable=false)
    public boolean isYear() {
        return this.year;
    }
    
    public void setYear(boolean year) {
        this.year = year;
    }




}


